---
title: "ConvHull"
author: "Fernanda Hansen"
date: "23 September 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r convhull, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
setwd("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/") # se no computador

# carrega os pacotes utilizados ----
source("01-call_packages.R")
source("02-funcoes.R")

path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/resultados/")

source("analises/ADNI_convhull.R")

paste("The number of subjects in ADNI is ", n_distinct(ADNI$SUBJ), ", and",length(ADNI$SUBJ) ," data points, with a mean age of", mean(ADNI$Age),"years old. This dataset has more than one session per subject.")

ADNI <- ADNI %>% group_by(SUBJ, hemi) %>% filter(aqc_date == min(aqc_date))

paste("The number of subjects in ADNI is ", n_distinct(ADNI$SUBJ), ", and",length(ADNI$SUBJ) ," data points, with a mean age of", mean(ADNI$Age),"years old. This dataset has only one session per subject.", "The maximum age is", max(ADNI$Age), ", and the minimum is", min(ADNI$Age))
      
ADNI_Ageinterval <- filter(ADNI, Age > 70 & Age < 75)

paste("The number of subjects in ADNI with the selected age interval is ", n_distinct(ADNI_Ageinterval$SUBJ), ", and", length(ADNI_Ageinterval$SUBJ) ," data points, with a mean age of", mean(ADNI_Ageinterval$Age),"years old. The maximum age is", max(ADNI_Ageinterval$Age), ", and the minimum is", min(ADNI_Ageinterval$Age))

lm_diag_ADNI_Ae <- ADNI_Ageinterval %>%
  group_by(Diagnostic) %>%
  do(fit_diag_ADNI_Ae = lm(1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea, data = .))

amostra_diag_ADNI_Ae_COEF = tidy(lm_diag_ADNI_Ae,
                                 fit_diag_ADNI_Ae,
                                 conf.int = TRUE,
                                 conf.level = 0.95)


ggplot(ADNI_Ageinterval, aes(
  logExposedArea,
  1 / 2 * logAvgThickness + logTotalArea, color = Diagnostic
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_pubclean()

amostra_diag_ADNI_Ae_COEF %>% kable(digits = 4) %>% kable_styling()

lm_diag_ADNI_CH <- ADNI_Ageinterval %>%
  group_by(Diagnostic) %>%
  do(fit_diag_ADNI_CH = lm(1 / 2 * logAvgThickness + logTotalArea ~ logConvexHullArea, data = .))

amostra_diag_ADNI_CH_COEF = tidy(lm_diag_ADNI_CH,
                                 fit_diag_ADNI_CH,
                                 conf.int = TRUE,
                                 conf.level = 0.95)

ggplot(ADNI_Ageinterval, aes(
  logConvexHullArea,
  1 / 2 * logAvgThickness + logTotalArea, color = Diagnostic
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

amostra_diag_ADNI_CH_COEF %>% kable(digits = 4) %>% kable_styling()


ggplot(ADNI_Ageinterval, aes(
  logConvexHullArea,
  logTotalArea, color = Diagnostic
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(ADNI_Ageinterval, aes(
  logConvexHullArea,
  logExposedArea, color = Diagnostic
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(ADNI_Ageinterval, aes(logConvexHullArea - logExposedArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3
)) +
  geom_density() +
  theme_pubclean()

```

