---
title: "ConvexHull"
author: "Fernanda Hansen"
date: "26 September 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho 
# setwd("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/R/aging/V6/")# se no idor
# setwd("E:/idor/Gyrification/") # se no pendrive
# setwd("C:/Users/fernanda.hansen/Desktop/aging/V6/") # se no pendrive
 setwd("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama as funcoes
source("02-funcoes.R")

# onde estao os arquivos de resultados:
# path <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/PROC_DATA/STATS/long_tables/")
 path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/resultados/")

# path_lobes <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/PROC_DATA/STATS/LobesScaling/")
 path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/resultados/")
 
# path_sessions <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/RAW_DATA/BIDS/")
 path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

# path_FA <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/RAW_DATA/BIDS/")
 path_FA <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/FA_CC/") 
 
# importa os resultados
source("03-import_files.R") # arquivos dos sujeitos

# organiza os arquivos
source("04-organiza.R")
# source("rotina_arquivos_neuroquant_comparisson.R")

dados_raw <- dados

verificar_lGI_zero <- filter(dados, localGI == 0 | is.na(localGI))
write.csv(verificar_lGI_zero, "verificar_lGI_zero.csv")

# retira os outros diagnosticos e deixa so quem tem machine definido
dados_all <- dados %>% filter(
    Diagnostic == "CONTROLE" |
      Diagnostic == "CCL" |
      Diagnostic == "ALZ", ExposedArea != 0 | !is.na(ExposedArea), !is.infinite(logExposedArea)) %>% 
  droplevels()

dados_excluidos <- anti_join(dados_raw, dados_all)
write.csv(dados_excluidos, "dados_excluidos.csv")

dados <- dados_all


# Prepara os dados para analise

# decaimento da idade
source("analises/decaimento_idade3.R")

# junta as amostras para comparacao
#source("analises/comp_samples.R")
dados$Diagnostic <- factor(dados$Diagnostic, levels = c("ALZ", "CCL","CONTROLE"))

dados <- filter(dados, machine == "Philips-Achieva", Longitudinal_correction == "yes")

# separa em arquivo de hemisferios e de lobos
dados_hemi_v1 <- filter(dados, ROI == "hemisphere", Session == 1, method == "FreeSurferStandard") %>% dplyr::select(
  SUBJ,
  acq_date,
  hemi,
  Age,
  Gender,
  Diagnostic,
  AvgThickness,
  logAvgThickness,
  TotalArea,
  logTotalArea,
  ExposedArea,
  logExposedArea,
  WhiteSurfArea,
  logWhiteSurfArea,
  logConvexHullArea,
  localGI ,
  K,
  Sample,
  logAvgThickness_age_decay,
  logTotalArea_age_decay,
  logExposedArea_age_decay,
  logConvexHullArea_age_decay,
  K_age_decay
  )
dados_hemi_v1_CH <- filter(dados, ROI == "hemisphere", Session == 1, method == "Yujiang_script") %>% dplyr::select(
  SUBJ,
  acq_date,
  hemi,
  Age,
  Gender,
  Diagnostic,
  AvgThickness,
  logAvgThickness,
  TotalArea,
  logTotalArea,
  ExposedArea,
  logExposedArea,
  WhiteSurfArea,
  ConvexHullArea,
  logWhiteSurfArea,
  logConvexHullArea,
  localGI ,
  K,
  Sample,
  logAvgThickness_age_decay,
  logTotalArea_age_decay,
  logExposedArea_age_decay,
  logConvexHullArea_age_decay,
  K_age_decay
  )

```

## IDOR sample and processing

```{r modelo_humanos, echo=FALSE, message=FALSE, warning=FALSE}

lm_fit_comp_idor <- dados_hemi_v1 %>%
  group_by(Diagnostic) %>%
  do(fit_comp_idor = lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit))


fit_comp_idor_Coef = tidy(lm_fit_comp_idor, fit_comp_idor,
                          conf.int = TRUE,
                          conf.level = 0.95)

ggplot(
  dados_hemi_v1,
  aes(logExposedArea, 1 / 2 * logAvgThickness + logTotalArea, color = Diagnostic, fill = Diagnostic )
  ) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + labs(caption = paste(
  "Humanos de todos os diagnosticos, apenas 1 visita, N = ",
   n_distinct(dados_hemi_v1$SUBJ)
  ))


fit_comp_idor_Coef %>% kable(digits = 4) %>% kable_styling()

paste("Verificando a diferenca entre o coeficiente obtido para a Sample e o teorico de 5/4, qual o valor p deste teste?", test_coef(lm(1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea, data = dados_hemi_v1, na.action = na.omit), 2, 1.25))

```

### All subjects that have a match

```{r all subjects that ahave a match in both samples, echo=FALSE, message=FALSE, warning=FALSE}

semi_join_dados_hemi_v1_CH <- semi_join(dados_hemi_v1, dados_hemi_v1_CH, by = "SUBJ", "acq_date", "hemi", "Diagnostic")

lm_fit_comp_idor <- semi_join_dados_hemi_v1_CH %>%
  group_by(Diagnostic) %>%
  do(fit_comp_idor = lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit))


fit_comp_idor_Coef = tidy(lm_fit_comp_idor, fit_comp_idor,
                          conf.int = TRUE,
                          conf.level = 0.95)

ggplot(
  semi_join_dados_hemi_v1_CH,
  aes(logExposedArea, 1 / 2 * logAvgThickness + logTotalArea, color = Diagnostic, fill = Diagnostic )
  ) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + labs(caption = paste(
  "Humanos de todos os diagnosticos, apenas 1 visita, N = ",
   n_distinct(semi_join_dados_hemi_v1_CH$SUBJ)
  ))

fit_comp_idor_Coef %>% kable(digits = 4) %>% kable_styling()

paste("Verificando a diferenca entre o coeficiente obtido para a Sample e o teorico de 5/4, qual o valor p deste teste?", test_coef(lm(1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea, data = semi_join_dados_hemi_v1_CH, na.action = na.omit), 2, 1.25))

```

## IDOR data, NC extracting script

```{r modelo_humanos CH , echo=FALSE, message=FALSE, warning=FALSE}

lm_fit_comp_idor_CH_AE <- dados_hemi_v1_CH %>%
  group_by(Diagnostic) %>%
  do(fit_comp_idor_CH_AE = lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit))


fit_comp_idor_CH_AE_Coef = tidy(lm_fit_comp_idor_CH_AE, fit_comp_idor_CH_AE,
                          conf.int = TRUE,
                          conf.level = 0.95)

ggplot(
  dados_hemi_v1_CH,
  aes(logExposedArea, 1 / 2 * logAvgThickness + logTotalArea, color = Diagnostic, fill = Diagnostic )
  ) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + labs(caption = paste(
  "Humanos de todos os diagnosticos, apenas 1 visita, N = ",
  n_distinct(dados_hemi_v1_CH$SUBJ)
  ))

fit_comp_idor_CH_AE_Coef %>% kable(digits = 4) %>% kable_styling()

paste("Verificando a diferenca entre o coeficiente obtido para a Sample e o teorico de 5/4, qual o valor p deste teste?", test_coef(lm(1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea, data = dados_hemi_v1_CH, na.action = na.omit), 2, 1.25))


lm_fit_comp_idor_CH <- dados_hemi_v1_CH %>%
  group_by(Diagnostic) %>%
  do(fit_comp_idor_CH = lm(1/2 * logAvgThickness + logTotalArea ~ logConvexHullArea, data = ., na.action = na.omit))


fit_comp_idor_CH_Coef = tidy(lm_fit_comp_idor_CH, fit_comp_idor_CH,
                          conf.int = TRUE,
                          conf.level = 0.95)

ggplot(
  dados_hemi_v1_CH,
  aes(logConvexHullArea, 1 / 2 * logAvgThickness + logTotalArea, color = Diagnostic, fill = Diagnostic )
  ) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + labs(caption = paste(
  "Humanos de todos os diagnosticos, apenas 1 visita, N = ",
  n_distinct(dados_hemi_v1_CH$SUBJ)
  ))

fit_comp_idor_CH_Coef %>% kable(digits = 4) %>% kable_styling()

paste("Verificando a diferenca entre o coeficiente obtido para a Sample e o teorico de 5/4, qual o valor p deste teste?", test_coef(lm(1 / 2 * logAvgThickness + logTotalArea ~ logConvexHullArea, data = dados_hemi_v1_CH, na.action = na.omit), 2, 1.25))

```

### IDOR data, NC extracting script - deaging

#### checking the deaging

```{r modelo_humanos CH - deaging check, echo=FALSE, message=FALSE, warning=FALSE}

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logAvgThickness, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logAvgThickness_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logTotalArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logTotalArea_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logExposedArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logExposedArea_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logConvexHullArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1_CH, Diagnostic == "CONTROLE"), aes(Age, logConvexHullArea_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

```
#### Results

```{r modelo_humanos CH - deaging, echo=FALSE, message=FALSE, warning=FALSE}

lm_fit_comp_idor_CH_AE <- dados_hemi_v1_CH %>%
  group_by(Diagnostic) %>%
  do(fit_comp_idor_CH_AE = lm(1/2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logExposedArea_age_decay, data = ., na.action = na.omit))


fit_comp_idor_CH_AE_Coef = tidy(lm_fit_comp_idor_CH_AE, fit_comp_idor_CH_AE,
                          conf.int = TRUE,
                          conf.level = 0.95)

ggplot(
  dados_hemi_v1_CH,
  aes(logExposedArea_age_decay, 1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay, color = Diagnostic, fill = Diagnostic )
  ) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + labs(caption = paste(
  "Humanos de todos os diagnosticos, apenas 1 visita, N = ",
  n_distinct(dados_hemi_v1_CH$SUBJ)
  ))

fit_comp_idor_CH_AE_Coef %>% kable(digits = 4) %>% kable_styling()

paste("Verificando a diferenca entre o coeficiente obtido para a Sample e o teorico de 5/4, qual o valor p deste teste?", test_coef(lm(1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logExposedArea_age_decay, data = dados_hemi_v1_CH, na.action = na.omit), 2, 1.25))


lm_fit_comp_idor_CH <- dados_hemi_v1_CH %>%
  group_by(Diagnostic) %>%
  do(fit_comp_idor_CH = lm(1/2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logConvexHullArea_age_decay, data = ., na.action = na.omit))


fit_comp_idor_CH_Coef = tidy(lm_fit_comp_idor_CH, fit_comp_idor_CH,
                          conf.int = TRUE,
                          conf.level = 0.95)

ggplot(
  dados_hemi_v1_CH,
  aes(logConvexHullArea_age_decay, 1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay, color = Diagnostic, fill = Diagnostic )
  ) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + labs(caption = paste(
  "Humanos de todos os diagnosticos, apenas 1 visita, N = ",
  n_distinct(dados_hemi_v1_CH$SUBJ)
  ))


fit_comp_idor_CH_Coef %>% kable(digits = 4) %>% kable_styling()

paste("Verificando a diferenca entre o coeficiente obtido para a Sample e o teorico de 5/4, qual o valor p deste teste?", test_coef(lm(1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logConvexHullArea_age_decay, data = dados_hemi_v1_CH, na.action = na.omit), 2, 1.25))

```

### Comparing with ADNI
```{r ADNI vs IDOR}
IDOR_CH <-
  dados_hemi_v1_CH

source("analises/ADNI_convhull.R")

data_comp <- full_join(ADNI, IDOR_CH)

data_comp$Diagnostic[data_comp$Diagnostic == "CONTROLE"] <- "Control"
data_comp$Diagnostic[data_comp$Diagnostic == "CCL"] <- "MCI"
data_comp$Diagnostic[data_comp$Diagnostic == "ALZ"] <- "AD"

data_comp <-
  mutate(
    data_comp,
    Sample = ifelse(
      Diagnostic == "Control" & Sample == "IDOR",
      "IDORControl",
      ifelse(
        Diagnostic == "MCI" & Sample == "IDOR",
        "IDORMCI",
        ifelse(
          Diagnostic == "AD" & Sample == "IDOR",
          "IDORAD",
          ifelse(
            Diagnostic == "Control" & Sample == "ADNI",
            "ADNIControl",
            ifelse(Diagnostic == "AD" & Sample == "ADNI",
                   "ADNIAD",
                   "")
          )
        )
      )
    )
  )

ggplot(data_comp, aes(Age, color = Sample, fill = Sample, alpha = 0.3
)) +
  geom_density() +
  theme_pubclean()

ggplot(data_comp, aes(Sample, Age, color = Sample, fill = Sample, alpha = 0.3
)) +
  geom_boxplot() + geom_point() +
  stat_compare_means(label = "p.signif", method = "t.test", hide.ns = TRUE, ref.group = "IDORControl") + stat_compare_means(method = "anova", label.x = "IDORControl") +
  theme_pubclean()

# ggplot(filter(data_comp, Age >= 70 & Age <= 75), aes(Sample, Age, color = Sample, fill = Sample, alpha = 0.3)) + geom_boxplot() + geom_point() + stat_compare_means(label = "p.signif", method = "t.test", hide.ns = TRUE, ref.group = "IDORControl") + stat_compare_means(method = "anova", label.x = "IDORControl") + theme_pubclean()

# ggplot(filter(data_comp, Age >= 70 & Age <= 75), aes(Age, color = Sample, fill = Sample, alpha = 0.3)) + geom_density() + theme_pubclean()

lm_diag_Ae <- data_comp %>%
  group_by(Sample) %>%
  do(fit_diag_Ae = lm(1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea, data = .))

amostra_diag_Ae_COEF = tidy(lm_diag_Ae,
                                 fit_diag_Ae,
                                 conf.int = TRUE,
                                 conf.level = 0.95)


ggplot(data_comp, aes(
  logExposedArea,
  1 / 2 * logAvgThickness + logTotalArea, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_pubclean()

ggplot(
  data = filter(amostra_diag_Ae_COEF, term == "logExposedArea"),
  aes(
  x = reorder(Sample, estimate),
  y = estimate,
  color = Sample
  )
  ) +
  geom_point() + geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + geom_hline(yintercept = 1.25, linetype = "dashed")  + stat_compare_means(method = "kruskal.test") + theme_pubclean() + labs(y = "slope")

amostra_diag_Ae_COEF %>% kable(digits = 4) %>% kable_styling()

lm_diag_CH <- data_comp %>%
  group_by(Sample) %>%
  do(fit_diag_CH = lm(1 / 2 * logAvgThickness + logTotalArea ~ logConvexHullArea, data = .))

amostra_diag_CH_COEF = tidy(lm_diag_CH,
                                 fit_diag_CH,
                                 conf.int = TRUE,
                                 conf.level = 0.95)

ggplot(data_comp, aes(
  logConvexHullArea,
  1 / 2 * logAvgThickness + logTotalArea, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(
  data = filter(amostra_diag_CH_COEF, term == "logConvexHullArea"),
  aes(
  x = reorder(Sample, estimate),
  y = estimate,
  color = Sample
  )
  ) +
  geom_point() + geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + geom_hline(yintercept = 1.25, linetype = "dashed")  + stat_compare_means(method = "kruskal.test") + theme_pubclean() + labs(y = "slope")

amostra_diag_CH_COEF %>% kable(digits = 4) %>% kable_styling()


ggplot(data_comp, aes(
  logConvexHullArea,
  logTotalArea, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(data_comp, aes(
  logConvexHullArea,
  logExposedArea, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(data_comp, aes(logConvexHullArea - logExposedArea, color = Sample, fill = Sample, alpha = 0.3
)) +
  geom_density() +
  theme_pubclean()


```

### Deaged

```{r ADNI vs IDOR deaged, echo=FALSE}

lm_diag_Ae <- data_comp %>%
  group_by(Sample) %>%
  do(fit_diag_Ae = lm(1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logExposedArea_age_decay, data = .))

amostra_diag_Ae_COEF = tidy(lm_diag_Ae,
                                 fit_diag_Ae,
                                 conf.int = TRUE,
                                 conf.level = 0.95)


ggplot(data_comp, aes(
  logExposedArea_age_decay,
  1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_pubclean()

ggplot(
  data = filter(amostra_diag_Ae_COEF, term == "logExposedArea_age_decay"),
  aes(
  x = reorder(Sample, estimate),
  y = estimate,
  color = Sample
  )
  ) +
  geom_point() + geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + geom_hline(yintercept = 1.25, linetype = "dashed")  + stat_compare_means(method = "kruskal.test") + theme_pubclean() + labs(y = "slope")

amostra_diag_Ae_COEF %>% kable(digits = 4) %>% kable_styling()

lm_diag_CH <- data_comp %>%
  group_by(Sample) %>%
  do(fit_diag_CH = lm(1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logConvexHullArea_age_decay, data = .))

amostra_diag_CH_COEF = tidy(lm_diag_CH,
                                 fit_diag_CH,
                                 conf.int = TRUE,
                                 conf.level = 0.95)

ggplot(data_comp, aes(
  logConvexHullArea_age_decay,
  1 / 2 * logAvgThickness_age_decay + logTotalArea_age_decay, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(
  data = filter(amostra_diag_CH_COEF, term == "logConvexHullArea_age_decay"),
  aes(
  x = reorder(Sample, estimate),
  y = estimate,
  color = Sample
  )
  ) +
  geom_point() + geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + geom_hline(yintercept = 1.25, linetype = "dashed")  + stat_compare_means(method = "kruskal.test") + theme_pubclean() + labs(y = "slope")

amostra_diag_CH_COEF %>% kable(digits = 4) %>% kable_styling()


ggplot(data_comp, aes(
  logConvexHullArea_age_decay,
  logTotalArea_age_decay, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(data_comp, aes(
  logConvexHullArea_age_decay,
  logExposedArea_age_decay, color = Sample
)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  theme_pubclean()

ggplot(data_comp, aes(logConvexHullArea_age_decay - logExposedArea_age_decay, color = Sample, fill = Sample, alpha = 0.3
)) +
  geom_density() +
  theme_pubclean()


```