---
title: "SI figures Paper1"
author: "Fernanda Hansen P. de Moraes"
date: "12/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep.R")

dados_datasetscomp <- filter(dados_datasetscomp, Sample == "IDOR" | Sample ==  "ADNI" | Sample ==  "AHEAD"| Sample ==  "AOMICPIOP1"| Sample ==  "HCP500r" | Sample ==  "NKI"| Sample ==  "OASIS", ROI == "hemisphere")

# dados_datasetscomp <- dados_datasetscomp %>% filter(Age == 18 | Age > 18)

# write.csv(dados_datasetscomp,"dados_datasetscomp.csv")
```

```{r}
filter(dados_datasetscomp,
       ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
    AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()
```


```{r}
dados_datasetscomp$Sample <- as.character(dados_datasetscomp$Sample)

dados_datasetscomp$Sample[dados_datasetscomp$Sample == "IDOR" &
                                  dados_datasetscomp$Diagnostic == "CTL"] <- "IDOR-Control"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "IDOR" &
                                  dados_datasetscomp$Diagnostic == "AD"] <- "IDOR-AD"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "IDOR" &
                                  dados_datasetscomp$Diagnostic == "MCI"] <- "IDOR-MCI"

dados_datasetscomp$Sample[dados_datasetscomp$Sample == "HCP500r"] <- "HCP500r-Control"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "OASIS"] <- "OASIS-Control"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "AOMICPIOP1"] <- "AOMICPIOP1-Control"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "AHEAD"] <- "AHEAD-Control"

dados_datasetscomp$Sample[dados_datasetscomp$Sample == "NKI"] <- "NKI-Control"

dados_datasetscomp$Sample[dados_datasetscomp$Sample == "ADNI" & dados_datasetscomp$Diagnostic == "AD"] <- "ADNI-AD"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "ADNI"& dados_datasetscomp$Diagnostic == "CTL"] <- "ADNI-Control"
```

# Mapping
```{r}
figS6a <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"),
                 aes(x = Age, y = K)) +
  geom_point(aes(color = Sample, fill = Sample)) +
  geom_smooth(color = "black", method = "lm") +
  theme_pubr() +
  guides(alpha = FALSE)+ 
  labs(x = "Age [years]") +
  theme(axis.title = element_text(size = 11),
        axis.text = element_text(size = 10), text = element_text(size = 10)) +
    scale_x_continuous(name ="Age", 
                    limits=c(0,100),
                breaks=c(seq(0,100,25)))
figS6a

cor.test(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$K, filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$Age)

figS6b <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"),
                 aes(x = Age, y = S)) +
  geom_point(aes(color = Sample, fill = Sample)) +
  geom_smooth(color = "black", method = "lm") +
  theme_pubr() +
  guides(alpha = FALSE, color = FALSE,fill = FALSE)+ 
  labs(x = "Age [years]") +
  theme(axis.title = element_text(size = 11),
        axis.text = element_text(size = 10), text = element_text(size = 10), legend.position= "none") +
    scale_x_continuous(name ="Age", 
                    limits=c(0,100),
                breaks=c(seq(0,100,25)))
figS6b

cor.test(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$S, filter(dados_datasetscomp, ROI == "hemisphere",  Diagnostic == "CTL")$Age)

figS6c <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"),
                 aes(x = Age, y = I)) +
  geom_point(aes(color = Sample, fill = Sample)) +
  geom_smooth(color = "black", method = "lm") +
theme_pubr() +
  guides(alpha = FALSE, color = FALSE,fill = FALSE)+ 
  labs(x = "Age [years]") +
  theme(axis.title = element_text(size = 11),
        axis.text = element_text(size = 10), text = element_text(size = 10), legend.position= "none") +
    scale_x_continuous(name ="Age", 
                    limits=c(0,100),
                breaks=c(seq(0,100,25)))
figS6c      

figS6 <- ggarrange(figS6a, ggarrange(figS6b, figS6c,labels = c("B","C"), nrow = 1, ncol = 2, font.label = list(size = 11)),labels = c("A"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")

figS6

ggsave("figS6.pdf", plot = figS6, dpi=1200, width = 17.8, height = 22, units = "cm", device = "pdf")
ggsave("figS6.jpeg", plot = figS6, dpi=1200, width = 17.8, height = 22, units = "cm", device = "jpeg")
ggsave("figS6.eps", plot = figS6, dpi=1200, width = 17.8, height = 22, units = "cm", device = "eps")
```

# AHEAD-Control

```{r}
Age_Coef_diag <- filter(dados_datasetscomp, ROI == "hemisphere", Sample == "AHEAD-Control") %>%
  group_by(Age_interval) %>%
  do(fit_Age_diag = tidy(lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit), conf.int = TRUE)) %>% unnest(fit_Age_diag)

Age_Coef_diag

N_subj_diag <- filter(dados_datasetscomp, ROI == "hemisphere", Sample == "AHEAD-Control") %>%
  group_by(Age_interval) %>%
  summarise(N_SUBJ = n_distinct(SUBJ))

figS5 <- ggplot(
  data = filter(Age_Coef_diag, term == "logExposedArea"),
  aes(
    x = Age_interval ,
    y = estimate
  )
) +
  geom_point() +
  geom_line(aes(group = 1)) +
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) +
  geom_text(aes(label = N_subj_diag$N_SUBJ), nudge_y = 0.17) +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() +
  labs(y = "Slope", x = "Age [years]") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9), axis.title = element_text(size = 11),  axis.text = element_text(size = 10), text = element_text(size = 10))

figS5

ggsave("figS5.pdf", dpi=1200, width = 11.4, height = 11.4, units = "cm", device = "pdf")
ggsave("figS5.jpeg", dpi=1200, width = 11.4, height = 11.4, units = "cm", device = "jpeg")
ggsave("figS5.eps", dpi=1200, width = 11.4, height = 11.4, units = "cm", device = "eps")
```

# AOMICPIOP1-Control

```{r}
Age_Coef_diag <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Sample == "AOMICPIOP1-Control" | Sample == "IDOR-Control", Age_interval != "80-85", Age_interval != "40-45") %>%
  group_by(Sample, Age_interval) %>%
  do(fit_Age_diag = tidy(lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>%
  unnest(fit_Age_diag)

# Age_Coef_diag

N_subj_diag <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Sample == "AOMICPIOP1-Control" | Sample == "IDOR-Control", Age_interval != "80-85", Age_interval != "40-45") %>%
  group_by(Sample, Age_interval) %>%
  summarise(N_SUBJ = n_distinct(SUBJ))

figS4a <- ggplot(
  data = filter(Age_Coef_diag, term == "logExposedArea"),
  aes(
    x = Age_interval ,
    y = estimate, color = Sample, fill = Sample
  )
) +
  geom_point() +
  geom_line(aes(group = Sample)) +
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) +
  geom_text(aes(label = N_subj_diag$N_SUBJ), nudge_y = 0.5) +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() +
  labs(y = "Slope", x = "Age [years]")  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9), axis.title = element_text(size = 11),  axis.text = element_text(size = 10), text = element_text(size = 10))
# + labs(caption = paste("N = ", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Sample == "AOMICPIOP1-Control" | Sample == "IDOR-Control")$SUBJ)))

figS4a

figS4b <- ggplot(
  filter(
    dados_datasetscomp,
    ROI == "hemisphere",
    Sample == "AOMICPIOP1-Control" | Sample == "IDOR-Control", Age_interval != "80-85", Age_interval != "40-45"
  ),
  aes(
    x = Age_interval ,
    y = logAvgThickness,
    color = Sample,
    fill = Sample, alpha = 0.5
  )
) +
  geom_boxplot() +
  theme_pubr() +
  labs(x = "Age [years]", y = expression("log"[10]*"CorticalThickness [mm]")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9), axis.title = element_text(size = 11),  axis.text = element_text(size = 10), text = element_text(size = 10))

figS4b

figS4c <- ggplot(
  filter(
    dados_datasetscomp,
    ROI == "hemisphere",
    Sample == "AOMICPIOP1-Control" | Sample == "IDOR-Control", Age_interval != "80-85", Age_interval != "40-45"
  ),
  aes(
    x = Age_interval ,
    y = K,
    color = Sample,
    fill = Sample, alpha = 0.5
  )
) +
  geom_boxplot() +
  theme_pubr() + labs(x = "Age [years]") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9), axis.title = element_text(size = 11),  axis.text = element_text(size = 10), text = element_text(size = 10))

figS4c

figS4 <- ggarrange(figS4a, figS4b, figS4c, labels = c("A","B", "C"), nrow = 1, ncol = 3, font.label = list(size = 11), common.legend = TRUE, legend = "top")

ggsave("figS4.pdf", dpi=1200, width = 17.8, height = 9, units = "cm", device = "pdf")
ggsave("figS4.jpeg", dpi=1200, width = 17.8, height = 9, units = "cm", device = "jpeg")
ggsave("figS4.eps", dpi=1200, width = 17.8, height = 9, units = "cm", device = "eps")

```

# Slopes

```{r}
amostras_Coef <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  group_by(Sample) %>%
  do(fit_amostras = tidy(lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit), conf.int = TRUE)) %>%
 unnest(fit_amostras) %>% filter(term == "logExposedArea")

amostras_Coef_age <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  group_by(Sample) %>%
  summarise(
    N = n_distinct(SUBJ),
    min_age = min(Age),
    max_age = max(Age))

amostras_Coef <- full_join(amostras_Coef, amostras_Coef_age)


figS3 <- ggplot(
  data = amostras_Coef,
  aes(
  x = reorder(Sample, estimate),
  y = estimate,
  )
  ) +
  geom_point() +
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  scale_x_discrete(labels = paste(amostras_Coef$Sample,"\n",amostras_Coef$N,", (",signif(amostras_Coef$min_age,2),"-",signif(amostras_Coef$max_age,2),")")) + 
 theme_pubr() +
  labs(y = "Slope", x = "Sample \n N, (age range)") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9), axis.title = element_text(size = 11),  axis.text = element_text(size = 10), text = element_text(size = 10))

figS3

ggsave("figS3.pdf", plot = figS3, dpi=1200, width = 17.8, height = 12, units = "cm", device = "pdf")
ggsave("figS3.jpeg", plot = figS3, dpi=1200, width = 17.8, height = 12, units = "cm", device = "jpeg")
ggsave("figS3.eps", plot = figS3, dpi=1200, width = 17.8, height = 12, units = "cm", device = "eps")

```

