---
title: "Relatorio PRJ Girificacao"
author: "Fernanda Hansen Pacheco de Moraes"
date: "11 de dezembro de 2018"
output:
  html_document:
    df_print: kable
    fig_caption: yes
    fig_width: 8
    number_sections: yes
    theme: paper
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: '5'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO --------

# define a area de trabalho ----
# setwd("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/R/aging/V6/")# se no idor
# setwd("E:/idor/Gyrification/") # se no pendrive
# setwd("C:/Users/fernanda.hansen/Desktop/aging/V6/") # se no pendrive
 setwd("~/idor/Gyrification/RRRRRR/aging/V6")

# carrega os pacotes utilizados ----
source("01-call_packages.R")

# Chama as funcoes ----
source("02-funcoes.R")

# onde estao os arquivos de resultados:
# path <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/PROC_DATA/STATS/long_tables/")
 path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/resultados/")

# path_lobes <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/PROC_DATA/STATS/LobesScaling/")
 path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/resultados/")
 
# path_sessions <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/RAW_DATA/BIDS/")
 path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

# path_FA <- str_c("Z:/PRJ1513_GIRIFICACAO_CONTROLES/03_PROCS/RAW_DATA/BIDS/")
 path_FA <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/FA_CC/") 
 
# importa os resultados ----
# source("03-import_files.R") # arquivos dos sujeitos
source("import.R") # arquivos dos sujeitos

# organiza os arquivos ----
# source("04-organiza.R")
# source("rotina_arquivos_neuroquant_comparisson.R")

dados_raw <- dados

verificar_lGI_zero <- filter(dados, localGI == 0 | is.na(localGI))
write.csv(verificar_lGI_zero, "verificar_lGI_zero.csv")

# retira os outros diagnosticos e deixa so quem tem machine definido
dados_all <- dados %>% filter(
    Diagnostic == "CONTROLE" |
      Diagnostic == "CCL" |
      Diagnostic == "ALZ", localGI != 0 | !is.na(localGI), !is.infinite(logExposedArea)) %>% 
  droplevels()

dados_excluidos <- anti_join(dados_raw, dados_all)
write.csv(dados_excluidos, "dados_excluidos.csv")

dados <- dados_all

Idade <- 25

# deixa so Philips

dados$Diagnostic[dados$Diagnostic == "CONTROLE"] <- "Control"
dados$Diagnostic[dados$Diagnostic == "ALZ"] <- "AD"
dados$Diagnostic[dados$Diagnostic == "CCL"] <- "MCI                "

dados$Diagnostic <- factor(dados$Diagnostic, levels = c("ALZ", "CCL","CONTROLE"))

dados <- filter(dados, machine == "Philips-Achieva")

# separa em arquivo de hemisferios e de lobos ----
dados_hemi_v1 <- filter(dados, ROI == "hemisphere")

dados_lobos_v1 <- filter(dados, ROI == "F" | ROI == "T" | ROI == "O" | ROI == "P")

```

```{r}
unique(dados$SUBJ)

```


# Resultados - com correcao longitudinal

### Apenas humanos IDOR

```{r modelo_humanos, echo=FALSE, message=FALSE, warning=FALSE}

lm_fit_comp_idor <- dados_hemi_v1 %>%
  group_by(Diagnostic) %>%
  do(fit_comp_idor = lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit))


# fit_comp_idor <- lm(1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea, data = dados_hemi_v1, na.action = na.omit)
# summary(fit_comp_idor)

fit_comp_idor_Coef = tidy(lm_fit_comp_idor, fit_comp_idor,
                          conf.int = TRUE,
                          conf.level = 0.95)

ggplot(
  dados_hemi_v1,
  aes(logExposedArea, 1 / 2 * logAvgThickness + logTotalArea, color = Diagnostic, fill = Diagnostic )
  ) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + labs(caption = paste(
  "Humanos de todos os diagnosticos, apenas 1 visita, N = ",
  n_distinct(dados_hemi_v1$SUBJ)
  ))

#+ geom_text(aes(label = ifelse((1 / 2 * logAvgThickness + logTotalArea)/(logExposedArea) < 1.2 ,as.character(SUBJ),'')))

fit_comp_idor_Coef %>% kable(digits = 4) %>% kable_styling()

paste("Verificando a diferenca entre o coeficiente obtido para a Sample e o teorico de 5/4, qual o valor p deste teste?", test_coef(lm(1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea, data = dados_hemi_v1, na.action = na.omit), 2, 1.25))

```

## Influencia do envelhecimento e diagnostico na girificacao
### Envelhecimento saudavel
```{r envelhecimento, echo=FALSE, message=FALSE, warning=FALSE}

paste("The mean age used for the deaging is ", mean(dados$Age), "years old.")

ggplot(data = dados_hemi_v1, aes(Diagnostic, Age, color = Diagnostic, fill = Diagnostic, alpha = 0.2)) +
  geom_boxplot() +
  theme_pubclean() + stat_compare_means(method = "anova", label.y = 88) +
  stat_compare_means(method = "t.test", label = "p.signif") + ylim(40, 90)

ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, AvgThickness, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()


ggplot(data = dados_hemi_v1, aes(Age, AvgThickness, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) + facet_grid(Diagnostic ~ .) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, logAvgThickness, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()


ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, logAvgThickness_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()


ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, logAvgThickness_age_decay - logAvgThickness, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, TotalArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, logTotalArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, logTotalArea_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, ExposedArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, logExposedArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()


ggplot(data = filter(dados_hemi_v1, Diagnostic == "CONTROLE"), aes(Age, logExposedArea_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()
```

### Girifcacao e envelhecimento

```{r girificacao e envelhecimento, echo=FALSE, message=FALSE, warning=FALSE}

lm_diagnostic <- dados_hemi_v1 %>%
  group_by(Sample) %>%
  do(fit_diagnostic = lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit))

diagnostic_Coef = tidy(lm_diagnostic,
                    fit_diagnostic,
                    conf.int = TRUE,
                    conf.level = 0.95)
diagnostic_Pred = augment(lm_diagnostic, fit_diagnostic)
diagnostic_R2 = glance(lm_diagnostic, fit_diagnostic)

diagnostic_Coef %>% kable(digits = 4) %>% kable_styling()

ggplot(data = dados_hemi_v1, aes(logExposedArea, 1/2 * logAvgThickness + logTotalArea, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = dados_hemi_v1, aes(Age, K, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

```

#### Reduzindo o efeito da idade

```{r girificacao e envelhecimento - age decay, echo=FALSE, message=FALSE, warning=FALSE}

lm_diagnostic_agedecay <- dados_hemi_v1 %>%
  group_by(Sample) %>%
  do(fit_diagnostic_agedecay = lm(1/2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logExposedArea_age_decay, data = ., na.action = na.omit))

diagnostic_Coef_agedecay = tidy(lm_diagnostic_agedecay,
                    fit_diagnostic_agedecay,
                    conf.int = TRUE,
                    conf.level = 0.95)

diagnostic_Coef_agedecay %>% kable(digits = 4) %>% kable_styling()

ggplot(data = dados_hemi_v1, aes(logExposedArea_age_decay, 1/2 * logAvgThickness_age_decay + logTotalArea_age_decay , color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + 
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

ggplot(data = dados_hemi_v1, aes(Age, K_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() + stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean()

```

### Podemos localizar partes com maior detrimento por idade e doenca?

```{r girificacao e lobos, echo=FALSE, message=FALSE, warning=FALSE}

dados_lobes <-
  filter(dados, Session == "1", ROI == "F" |
  ROI == "T" | ROI == "O" | ROI == "P" | ROI == "hemisphere") %>%
  droplevels()
  
# dados_lobes <- ordered(dados_lobes, levels = c("hemisphere", "F", "O", "P","T"))

lm_diagnostic_lobe <- dados_lobes %>%
  group_by(ROI, Diagnostic) %>%
  do(
  fit_diagnostic_lobe = lm(
  1 / 2 * logAvgThickness + logTotalArea ~ logExposedArea,
  data = .,
  na.action = na.omit
  )
  )
  
diagnostic_Coef_lobe = tidy(
  lm_diagnostic_lobe,
  fit_diagnostic_lobe,
  conf.int = TRUE,
  conf.level = 0.95
  )
  
# diagnostic_Coef_lobe %>% kable(digits = 4) %>% kable_styling()

ggplot(data = filter(dados_lobes, Diagnostic == "CONTROLE"), aes(logExposedArea, 1/2 * logAvgThickness + logTotalArea, color = ROI, fill = ROI, alpha = 0.3)) +
  geom_point() + geom_smooth(method = "lm", se = TRUE) +
  geom_abline(slope = filter(diagnostic_Coef_lobe, term == "logExposedArea", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate, linetype = "dashed", intercept = filter(diagnostic_Coef_lobe, term == "(Intercept)", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate) +
  stat_regline_equation() +
  theme_pubclean()
  
#+ geom_abline(slope = 1.25, linetype = "dashed", intercept =  filter(diagnostic_Coef_lobe, term == "(Intercept)", Diagnostic == "CONTROLE")$estimate)

ggplot(
  data = dados_lobes,
  aes(
  logExposedArea,
  1 / 2 * logAvgThickness + logTotalArea,
  color = Diagnostic,
  fill = Diagnostic,
  alpha = 0.3
  )
  ) +
  geom_point() +
  geom_abline(slope = filter(diagnostic_Coef_lobe, term == "logExposedArea", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate, linetype = "dashed", intercept = filter(diagnostic_Coef_lobe, term == "(Intercept)", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate) +
  stat_regline_equation() + 
  facet_wrap(ROI ~ .) +
  theme_pubclean() 

ggplot(
  data = filter(diagnostic_Coef_lobe, term == "logExposedArea"),
  aes(
  x = reorder(Diagnostic, estimate),
  y = estimate,
  color = Diagnostic
  )
  ) +
  geom_point() + 
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + 
  geom_hline(yintercept = 1.25, linetype = "dashed")  + 
  stat_compare_means(method = "kruskal.test") + 
  labs(y = "slope") + 
  facet_wrap(ROI ~. ) + 
  theme_pubclean()

```

#### Corrigindo pela curvatura

```{r girificaca e lobos - corrigido pela curvatura, echo=FALSE, message=FALSE, warning=FALSE}
lm_diagnostic_lobe_curv <- dados_lobes %>%
  group_by(ROI, Diagnostic) %>%
  do(fit_diagnostic_lobe_curv = lm(1/2 * logAvgThickness + logTotalArea_corrected ~ logExposedArea_corrected, data = ., na.action = na.omit))

diagnostic_Coef_lobe_curv = tidy(lm_diagnostic_lobe_curv,
                    fit_diagnostic_lobe_curv,
                    conf.int = TRUE,
                    conf.level = 0.95)

# diagnostic_Coef_lobe_curv %>% kable(digits = 4) %>% kable_styling()

ggplot(data = filter(dados_lobes, Diagnostic == "CONTROLE"), aes(logExposedArea_corrected, 1/2 * logAvgThickness + logTotalArea_corrected, color = ROI, fill = ROI, alpha = 0.3)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  geom_abline(slope = filter(diagnostic_Coef_lobe_curv, term == "logExposedArea_corrected", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate, linetype = "dashed", intercept = filter(diagnostic_Coef_lobe_curv, term == "(Intercept)", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate) + 
  stat_regline_equation() + 
  theme_pubclean()

ggplot(data = dados_lobes, aes(logExposedArea_corrected, 1/2 * logAvgThickness + logTotalArea_corrected, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE)  +
  geom_abline(slope = filter(diagnostic_Coef_lobe_curv, term == "logExposedArea_corrected", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate, linetype = "dashed", intercept = filter(diagnostic_Coef_lobe_curv, term == "(Intercept)", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate) +
  stat_regline_equation() + 
  theme_pubclean() + facet_wrap(ROI ~. )

ggplot(
  data = filter(diagnostic_Coef_lobe_curv, term == "logExposedArea_corrected"),
  aes(
  x = reorder(Diagnostic, estimate),
  y = estimate,
  color = Diagnostic
  )
  ) +
  geom_point() + geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + stat_compare_means(method = "kruskal.test") + theme_pubclean() + labs(y = "slope") + facet_wrap(ROI ~. )

ggplot(data = dados_lobes, aes(Age, K_corrected,color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_smooth(method = "lm", se = TRUE) + stat_cor() +
  theme_pubclean() + facet_wrap(ROI ~. )
```

#### Corrigindo pela idade 

```{r girificaca e lobos - age decay, echo=FALSE, message=FALSE, warning=FALSE}
lm_diagnostic_agedecay_lobe <- dados_lobes %>%
  group_by(ROI, Diagnostic) %>%
  do(fit_diagnostic_agedecay_lobe = lm(1/2 * logAvgThickness_age_decay + logTotalArea_age_decay ~ logExposedArea_age_decay, data = ., na.action = na.omit))

diagnostic_Coef_agedecay_lobe = tidy(lm_diagnostic_agedecay_lobe,
                    fit_diagnostic_agedecay_lobe,
                    conf.int = TRUE,
                    conf.level = 0.95)

# diagnostic_Coef_agedecay_lobe %>% kable(digits = 4) %>% kable_styling()

ggplot(data = filter(dados_lobes, Diagnostic == "CONTROLE"), aes(logExposedArea_age_decay, 1/2 * logAvgThickness_age_decay + logTotalArea_age_decay, color = ROI, fill = ROI, alpha = 0.3)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  geom_abline(slope = filter(diagnostic_Coef_agedecay_lobe, term == "logExposedArea_age_decay", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate, linetype = "dashed", intercept = filter(diagnostic_Coef_agedecay_lobe, term == "(Intercept)", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate) +
  stat_regline_equation() + 
  theme_pubclean()

ggplot(data = dados_lobes, aes(logExposedArea_age_decay, 1/2 * logAvgThickness_age_decay + logTotalArea_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  geom_abline(slope = filter(diagnostic_Coef_agedecay_lobe, term == "logExposedArea_age_decay", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate, linetype = "dashed", intercept = filter(diagnostic_Coef_agedecay_lobe, term == "(Intercept)", Diagnostic == "CONTROLE", ROI == "hemisphere")$estimate) +
  stat_regline_equation() + 
  theme_pubclean() + facet_wrap(ROI ~. )

ggplot(
  data = filter(diagnostic_Coef_agedecay_lobe, term == "logExposedArea_age_decay"),
  aes(
  x = reorder(Diagnostic, estimate),
  y = estimate,
  color = Diagnostic
  )
  ) +
  geom_point() + geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + geom_hline(yintercept = 1.25, linetype = "dashed")  + stat_compare_means(method = "kruskal.test") + theme_pubclean() + labs(y = "slope") + facet_wrap(ROI ~. )

ggplot(data = filter(dados_lobes, Diagnostic == "CONTROLE"), aes(Age, K, alpha = 0.3)) +
  geom_smooth(se = TRUE) +
  stat_regline_equation() + stat_cor() +
  theme_pubclean() + facet_wrap(ROI ~ . )

ggplot(data = filter(dados_lobes, Diagnostic == "CONTROLE"), aes(Age, K_age_decay, alpha = 0.3)) +
  geom_smooth(se = TRUE) +
  stat_regline_equation() +
  theme_pubclean() + facet_wrap(ROI ~ . )

ggplot(data = dados_lobes, aes(Age, K_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.3)) +
  stat_regline_equation() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_pubclean() + facet_wrap(ROI ~ . )
```

