---
title: "AD_ADNI_IDOR"
author: "Fernanda Hansen P. de Moraes"
date: "23/06/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep_ADNI.R")

dados_datasetscomp <- dados_datasetscomp %>%
   filter(Sample == "ADNI" | Sample == "IDOR")  %>% 
   # dplyr::select(c(machine, SUBJ, Age, Gender, Diagnostic, Sample, ROI, hemi, AvgThickness, TotalArea, ExposedArea, GMvolume, logAvgThickness, logTotalArea, logExposedArea, localGI, k, K, S, I, Knorm, Snorm, Inorm, c, TotalArea_corrected, ExposedArea_corrected, logTotalArea_corrected, logExposedArea_corrected, localGI_corrected, K_corrected, S_corrected, I_corrected, APOE4, MMSE, FLDSTRENG, FSVERSION, ABETA, TAU, PTAU, `AB1-42`, localGI_age_decay, localGI_shiftc, localGI_age_decay_shiftc, K_age_decay, K_shiftc, K_age_decay_shiftc, I_age_decay, I_shiftc, I_age_decay_shiftc, S_age_decay, S_shiftc, S_age_decay_shiftc, Knorm_shiftc, Snorm_shiftc, Inorm_shiftc, Knorm_age_decay, Snorm_age_decay, Inorm_age_decay, Knorm_age_decay_shiftc, Snorm_age_decay_shiftc, Inorm_age_decay_shiftc, Age_interval10, Age_interval)) %>%
   mutate(
     ABETA = ifelse(Sample == "ADNI", ABETA, `AB1-42`),
     TAU = as.double(TAU),
     TAU_AB1_42_ratio = TAU/ABETA)

dados_datasetscomp$Diagnostic <- factor(dados_datasetscomp$Diagnostic, levels = c("CTL", "MCI", "AD"))

dados_ADNI <- dados_datasetscomp %>%
  filter(Sample == "ADNI", ROI == "hemisphere") %>%
  dplyr::select(c(SUBJ, Age, Gender, Diagnostic, Sample, ROI, hemi, AvgThickness, TotalArea, ExposedArea, GMvolume, k, K, S, I, MMSE, ABETA, TAU, Age_interval10, Age_interval)) 

write.csv(dados_ADNI, "dados_ADNI.csv")
```

# Data description

```{r}
filter(dados_datasetscomp, ROI == "hemisphere") %>%
  group_by(Diagnostic, Sample) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
#   age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
    AvgT = paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
# AT = paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
# AE = paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    K = paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    S = paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    I = paste(signif(mean(I), 2), "±", signif(sd(I), 2)),
    TAU = paste(signif(mean(TAU, na.rm = TRUE), 2), "±", signif(sd(TAU, na.rm = TRUE), 2)),
    ABETA = paste(signif(mean(ABETA, na.rm = TRUE), 2), "±", signif(sd(ABETA, na.rm = TRUE), 2)),
    TAU_AB1_42_ratio  = paste(signif(mean(TAU_AB1_42_ratio, na.rm = TRUE), 2), "±", signif(sd(TAU_AB1_42_ratio, na.rm = TRUE), 2))
  ) %>% kable(digits = 2) %>% kable_styling()
```

```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = Sample, y = ABETA, color = factor(Diagnostic))) +
  geom_boxplot() +
  theme_pubr() +
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
    )

ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = Sample, y = TAU, color = factor(Diagnostic))) +
  geom_boxplot() +
  theme_pubr() +
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
    )

ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = Sample, y = TAU_AB1_42_ratio , color = factor(Diagnostic))) +
  geom_boxplot() +
  theme_pubr() +
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
    )

```

# How to define CTL A+ or T+? What should be the cutoff?

# Is K different in CTL with A+ or T+?

```{r}

dados_datasetscomp <- dados_datasetscomp %>%
  group_by(Sample, Diagnostic) %>%
  mutate(max_ABETA = max(ABETA, na.rm = TRUE),
         min_TAU = min(TAU, na.rm = TRUE),
         min_TAU_ABETA_ratio = min(TAU_AB1_42_ratio, na.rm = TRUE))
         

ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = K, y = ABETA, color = Diagnostic, fill = Diagnostic)) +
  geom_point() +
  geom_hline(aes(yintercept = max_ABETA, color = Diagnostic)) +
  stat_cor() +
  theme_pubr() +
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
    ) + facet_wrap(Sample ~.)

ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = K, y = TAU, color = Diagnostic, fill = Diagnostic)) +
  geom_point() +
  geom_hline(aes(yintercept = min_TAU, color = Diagnostic)) +
  stat_cor() +
  theme_pubr() +
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
    ) + facet_wrap(Sample ~.)

ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = K, y = TAU_AB1_42_ratio , color = Diagnostic, fill = Diagnostic)) +
  geom_point() +
    geom_hline(aes(yintercept = min_TAU_ABETA_ratio, color = Diagnostic)) +
  stat_cor() +
  theme_pubr() +
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
    ) + facet_wrap(Sample ~.)

```

# AGE
```{r}
ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Snorm_age_decay, color = Diagnostic, size = as.numeric(Age_interval10), alpha = 0.5)) +
  geom_point() +
  theme_pubr()+
  labs(size = "Age") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Inorm_age_decay, color = Diagnostic, size = as.numeric(Age_interval10), alpha = 0.5)) +
  geom_point() +
  theme_pubr() +
  labs(size = "Age") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)
```

# TAU
```{r}
ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Snorm_age_decay, color = Diagnostic, size = as.numeric(TAU), alpha = 0.5)) +
  geom_point() +
  theme_pubr()+
  labs(size = "TAU") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Inorm_age_decay, color = Diagnostic, size = as.numeric(TAU), alpha = 0.5)) +
  geom_point() +
  theme_pubr() +
  labs(size = "TAU") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)
```

```{r}
ggplot(data = dados_datasetscomp, aes(Age, TAU, alpha = 0.5, color = Diagnostic, fill = Diagnostic)) +
  geom_point(aes(shape = Sample)) +
  geom_smooth() +
  theme_pubr()+
  guides(alpha = "none") +
  scale_y_log10()
```

# ABETA
```{r}
ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Snorm_age_decay, color = Diagnostic, size = as.numeric(ABETA), alpha = 0.5)) +
  geom_point() +
  theme_pubr()+
  labs(size = "ABETA") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Inorm_age_decay, color = Diagnostic, size = as.numeric(ABETA), alpha = 0.5)) +
  geom_point() +
  theme_pubr() +
  labs(size = "ABETA") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)
```

# MMSE
```{r}
ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Snorm_age_decay, color = Diagnostic, size = as.numeric(MMSE), alpha = 0.5)) +
  geom_point() +
  theme_pubr()+
  labs(size = "MMSE") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Inorm_age_decay, color = Diagnostic, size = as.numeric(
MMSE
), alpha = 0.5)) +
  geom_point() +
  theme_pubr() +
  labs(size = "MMSE") +
  guides(alpha = "none") +
  facet_wrap(Sample ~.)
```

# Hippocampus volume /ICV
```{r eval=FALSE, include=FALSE}
ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Snorm_age_decay, color = Diagnostic, size = Hippocampus/ICV, alpha = 0.5)) +
  geom_point() +
  theme_pubr()+
  labs(size = "Hippocampus/ICV") +
  guides(alpha = "none")

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Knorm_age_decay, Inorm_age_decay, color = Diagnostic, size = Hippocampus/ICV, alpha = 0.5)) +
  geom_point() +
  theme_pubr() +
  labs(size = "Hippocampus/ICV") +
  guides(alpha = "none")
```
