---
title: "Typical"
author: "Fernanda Hansen P. de Moraes"
date: "05/03/2021"
output: 
  html_document: 
    toc: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE,
                      warning=FALSE,
                      cache=TRUE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

set.seed(1)

# Prepara os dados para analise
source("05-analises_prep.R")

# dados_datasetscomp <- dados_datasetscomp %>%
#   filter(Sample != "HCP500r",
#          Diagnostic != "MCI")

dados_datasetscomp <- dados_datasetscomp %>%
  filter(Sample != "HCP500r")

dados_datasetscomp$Diagnostic <- relevel(dados_datasetscomp$Diagnostic, ref = "CTL")

# dados_datasetscomp <- dados_datasetscomp %>% filter(Age == 18 | Age > 18)

# write.csv(dados_datasetscomp,"dados_datasetscomp.csv")

```

# Datasets description

We included multiple datasets from different sites to estimate, accounting methodological and "subject" biases, typical values for K, S and I.

```{r description, eval=FALSE, include=FALSE}
filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp,
       Sample != "Mota&Houzel2015",
       ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
    AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()


filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()
```
# Mapping

## CTL

```{r}
paste("N SUBJ", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))
paste("mean age", mean(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$Age), ", sd = ", sd(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$Age))

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness))) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm", color = "black")+
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_regline_equation()

lm <- lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), data = filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]"), na.action = na.omit)

summary(lm)
tidy(lm)

#lm <- lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), na.action = na.omit)

#summary(lm)
#tidy(lm)

amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval) %>%
    do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness) + log10(TotalArea) ~ log10(ExposedArea), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>% filter(term == "log10(ExposedArea)")

ggplot(amostra_Coef, aes(y = estimate, x = Age_interval)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope", x = "Age interval") +
  geom_text(aes(label = N), nudge_y = 0.3) +
  geom_line(group = 0)

# amostra_Coef %>% dplyr::select(-c(term)) %>% kable() %>% kable_styling()

```

### per subject
```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI != "hemisphere", Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
  group_by(SUBJ) %>%
  do(fit_amostra = tidy(lm(1/2 * logAvgThickness + logTotalArea_corrected ~ logExposedArea_corrected, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(filter(amostra_Coef, term == "logExposedArea_corrected"), aes(x = estimate, alpha = 0.3)) +
  geom_histogram() +
  geom_vline(xintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)) +
  labs(x ="Slope", x = "Age interval") +
  guides(alpha = "none")
```

#### correction factor lobes

```{r echo=FALSE}
# ggplot(filter(dados_datasetscomp, ROI != "hemisphere"), aes(x = ROI, y = c, color = Sample)) +
#   geom_boxplot() +
#   geom_jitter() +
#   theme_pubr()

dados_datasetscomp_lobes_cov <- dados_datasetscomp %>%
  group_by(SUBJ) %>%
  mutate(
    var = var(log10(c), na.rm = TRUE),
    var_harm = var(log10(c_shiftc), na.rm = TRUE),
    logAE = log10(ExposedArea_corrected),
    logAT.T = log10(TotalArea_corrected * sqrt(AvgThickness))
   #, cov = cov(logAE, logAT.T)
  ) %>%
  unique()

# ggplot(filter(dados_datasetscomp_lobes_cov, ROI != "hemisphere"), aes(x = var, alpha = 0.3)) +
#   geom_histogram() +
#   theme_pubr() + 
#   guides(alpha = "none") 
# + facet_wrap(Sample ~ .)

# ggplot(filter(dados_datasetscomp_lobes_cov, ROI != "hemisphere"), aes(x = var, y = var_harm)) +
#   geom_point(aes(color = Sample)) +
#   stat_regline_equation() +
#   theme_pubr()

dados_datasetscomp_lobes <- filter(dados_datasetscomp_lobes_cov, ROI != "hemisphere") %>% 
  dplyr::select(c(SUBJ, logAE, logAT.T))
# %>% unite(Sample_ROI, Sample, ROI, sep = "_")

dados_datasetscomp_lobesList <- split(dados_datasetscomp_lobes[ ,c("logAE", "logAT.T")], list(Group = dados_datasetscomp_lobes$SUBJ))

within.group.cov <- lapply(dados_datasetscomp_lobesList , function(x) cov(x[c("logAE", "logAT.T")], use="pairwise.complete.obs"))

cov <- as.data.frame(unlist(within.group.cov, recursive = TRUE, use.names = TRUE))
cov$SUBJ_n <- row.names(cov)   
colnames(cov)[1] <- "delta"

cov <- cov %>%
  separate(SUBJ_n,into = c("SUBJ", "n"), sep = -1) %>%
  pivot_wider(names_from = n, values_from = delta, names_prefix = "delta")

dados_datasetscomp_lobes_cov <- full_join(dados_datasetscomp_lobes_cov, cov) %>%
  mutate(gama_harm = (delta1-delta4)/(2*delta2-var_harm),
         alpha_lobes_harm = 1/(gama_harm+sqrt(1+gama_harm^2)),
         gama = (delta1-delta4)/(2*delta2-var),
         alpha_lobes = 1/(gama+sqrt(1+gama^2)))

ggplot(filter(dados_datasetscomp_lobes_cov, ROI != "hemisphere"), aes(x = alpha_lobes, alpha = 0.3)) +
  geom_histogram() +
  geom_vline(xintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)) +
  labs(x ="Slope lobes") +
  guides(alpha = "none")

ggplot(filter(dados_datasetscomp_lobes_cov, ROI != "hemisphere"), aes(x = alpha_lobes_harm, alpha = 0.3)) +
  geom_histogram() +
  geom_vline(xintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)) +
  labs(x ="Slope lobes (harmonized)") +
  guides(alpha = "none")

```


```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval, Diagnostic) %>%
    do(fit_amostra = tidy(lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(dados_datasetscomp, ROI == "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval, Diagnostic) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>% filter(term == "logExposedArea")

amostra_Coef$Diagnostic <- factor(amostra_Coef$Diagnostic, levels=c('AD', 'MCI', 'CTL'))

ggplot(amostra_Coef, aes(y = estimate, x = Age_interval, color = Diagnostic)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point() +
  geom_line(aes(group = Diagnostic)) +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope", x = "Age interval")

# amostra_Coef %>% dplyr::select(-c(term)) %>% kable() %>% kable_styling()

```

```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]", Age > 50) %>%
    group_by(Age_interval, Diagnostic) %>%
    do(fit_amostra = tidy(lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(dados_datasetscomp, ROI == "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval, Diagnostic) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>% filter(term == "logExposedArea")

ggplot(amostra_Coef, aes(y = estimate, x = Age_interval)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope", x = "Age interval") +
  geom_text(aes(label = N), nudge_y = 0.3) +
  geom_line(group = 0) + 
  facet_wrap(Diagnostic ~ .)


# amostra_Coef %>% dplyr::select(-c(term)) %>% kable() %>% kable_styling()

```

```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]", Age > 50) %>%
    group_by(Age_interval, Diagnostic) %>%
    do(fit_amostra = tidy(lm(1/2 * logExposedArea_shiftc + logTotalArea_shiftc ~ logExposedArea_shiftc, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(dados_datasetscomp, ROI == "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval, Diagnostic) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>% filter(term == "logExposedArea_shiftc")

ggplot(amostra_Coef, aes(y = estimate, x = Age_interval)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope (harmonized)", x = "Age interval") +
  geom_text(aes(label = N), nudge_y = 0.3) +
  geom_line(group = 0) + 
  facet_wrap(Diagnostic ~ .)

```

## LOBES

```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI != "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]", Age > 50) %>%
    group_by(Age_interval, Diagnostic, ROI) %>%
    do(fit_amostra = tidy(lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostra_Coef <-amostra_Coef %>% filter(term == "logExposedArea")

ggplot(filter(amostra_Coef, estimate > 1), aes(y = estimate, x = Age_interval, color = ROI)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope", x = "Age interval") +
  geom_line(aes(group = ROI)) + 
  facet_wrap(Diagnostic ~ .)

ggplot(filter(amostra_Coef, estimate > 1), aes(y = estimate, x = Age_interval, color = Diagnostic)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point(alpha = 0.4) +
  guides(alpha = "none") +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope", x = "Age interval") +
  geom_line(aes(group = Diagnostic)) + 
  facet_wrap(ROI ~ .)

# amostra_Coef %>% dplyr::select(-c(term)) %>% kable() %>% kable_styling()

```

```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI != "hemisphere", Age_interval != "[0,5)", Age_interval != "[95,100]", Age > 50) %>%
    group_by(Age_interval, Diagnostic, ROI) %>%
    do(fit_amostra = tidy(lm(1/2 * logAvgThickness_shiftc + logTotalArea_shiftc ~ logExposedArea_shiftc, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostra_Coef <- amostra_Coef %>% filter(term == "logExposedArea_shiftc")

ggplot(filter(amostra_Coef, estimate < 2, estimate > 1), aes(y = estimate, x = Age_interval, color = ROI)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope (harmonized)", x = "Age interval") +
  geom_line(aes(group = ROI)) + 
  facet_wrap(Diagnostic ~ .)

ggplot(filter(amostra_Coef, estimate < 2, estimate > 1), aes(y = estimate, x = Age_interval, color = Diagnostic)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_point(alpha = 0.4) +
  guides(alpha = "none") +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="Slope (harmonized)", x = "Age interval") +
  geom_line(aes(group = Diagnostic)) + 
  facet_wrap(ROI ~ .)

# amostra_Coef %>% dplyr::select(-c(term)) %>% kable() %>% kable_styling()

```