---
title: "Typical"
author: "Fernanda Hansen P. de Moraes"
date: "05/03/2021"
output: 
  html_document: 
    toc: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      cache = TRUE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep_ALL.R")

dados_datasetscomp <- dados_datasetscomp %>%
  filter(Sample != "HCP500r")
 
outlier <- dados_datasetscomp %>%  
   filter(Family == "Hominidae" & K < -0.7)

dados_datasetscomp <- anti_join(dados_datasetscomp, outlier)

# dados_datasetscomp <- dados_datasetscomp %>% filter(Age == 18 | Age > 18)

# write.csv(dados_datasetscomp,"dados_datasetscomp.csv")
```

# Datasets description

We included multiple datasets from different sites to estimate, accounting methodological and "subject" biases, typical values for K, S and I.

```{r description, include=FALSE}
filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp,
       Sample != "Mota&Houzel2015",
       ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
    AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()


filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()
```

# Cetaceans
```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness))) +
  geom_point(aes(color = Family)) +
  geom_point(data = subset(dados_datasetscomp, Family != "Cetacea" & Family != "Cetacea K" & Family != "Hominidae"), color = "black") +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_regline_equation() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness))) +
  geom_point(aes(color = Family)) +
  geom_point(data = subset(dados_datasetscomp, Family != "Cetacea" & Family != "Cetacea K" & Family != "Hominidae"), color = "black") +
  scale_x_log10(limits = c(3000, 100000)) +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness), color = Family, fill = Family)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm", color = "black", fill = "black", alpha = 0.6) +
  stat_smooth(data = subset(dados_datasetscomp, Family == "Cetacea" | Family == "Cetacea K"), method = "lm", alpha = 0.6) +
  guides(alpha = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))
```

Verificando o expoente com o desvio padrao:
```{r}
lm <- lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), filter(dados_datasetscomp, ROI == "hemisphere"))
summary(lm)
```

```{r}
cor <- cor.test(log10(filter(dados_datasetscomp, ROI == "hemisphere")$ExposedArea), log10(filter(dados_datasetscomp, ROI == "hemisphere")$TotalArea*sqrt(filter(dados_datasetscomp, ROI == "hemisphere")$AvgThickness)))
cor
paste("R2 = ", signif(cor$estimate^2, 2))
```

## só cetaceos
Mota & Houzel:

```{r}
lm <- lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea"))
summary(lm)
```

```{r}
cor <- cor.test(log10(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea" )$ExposedArea), log10(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea")$TotalArea*sqrt(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea")$AvgThickness)))
cor
paste("R2 = ", signif(cor$estimate^2, 2))
```

Kamilla:
```{r}
lm <- lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K"))
summary(lm)
```

```{r}
cor <- cor.test(log10(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K")$ExposedArea), log10(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K")$TotalArea*sqrt(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K")$AvgThickness)))
cor
paste("R2 = ", signif(cor$estimate^2, 2))
```

# Boxplot

## K

```{r echo=FALSE}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = Family, y = K, alpha = 0.4, color = Diagnostic, fill = Diagnostic))+
  geom_boxplot() +
  theme_pubr() + 
  guides(alpha = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

```

t test:

```{r}
filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K" |  Family == "Cetacea") %>%
  t_test(K ~ Family, var.equal = TRUE) %>%
  add_significance()

```


```{r}
filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K" |  Family == "Cetacea") %>%
mann  (K ~ Family, var.equal = TRUE) %>%
  add_significance()

```

cohen's D:

```{r}

filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K" |  Family == "Cetacea") %>%
  cohens_d(K ~ Family, var.equal = TRUE)

```

## S
```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = Family, y = S, alpha = 0.4, color = Diagnostic, fill = Diagnostic))+
  geom_boxplot() +
  theme_pubr() + 
  guides(alpha = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))
```

t test:

```{r}
filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K" |  Family == "Cetacea") %>%
  t_test(S ~ Family, var.equal = TRUE) %>%
  add_significance()

```

cohen's D:

```{r}

filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K" |  Family == "Cetacea") %>%
  cohens_d(S ~ Family, var.equal = TRUE)

```

## I

```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(x = Family, y = I, alpha = 0.4, color = Diagnostic, fill = Diagnostic))+
  geom_boxplot() +
  theme_pubr() + 
  guides(alpha = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))
```

t test:

```{r}
filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K" |  Family == "Cetacea") %>%
  t_test(I ~ Family, var.equal = TRUE) %>%
  add_significance()

```

cohen's D:

```{r}

filter(dados_datasetscomp, ROI == "hemisphere", Family == "Cetacea K" |  Family == "Cetacea") %>%
  cohens_d(I ~ Family, var.equal = TRUE)

```