---
title: "Typical"
author: "Fernanda Hansen P. de Moraes"
date: "05/03/2021"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep_ALL.R")

dados_datasetscomp <- dados_datasetscomp %>% filter(Sample != "HCP500r")

# dados_datasetscomp <- dados_datasetscomp %>% filter(Age == 18 | Age > 18)

# write.csv(dados_datasetscomp,"dados_datasetscomp.csv")
```

# Datasets description

We included multiple datasets from different sites to estimate, accounting methodological and "subject" biases, typical values for K, S and I.

```{r description, echo=FALSE}
filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

# filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
#   summarise(
#     N = n_distinct(SUBJ),
#     age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
#     age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
# ) %>% kable(digits = 2) %>% kable_styling()
# 
# filter(dados_datasetscomp,
#        Sample != "Mota&Houzel2015",
#        ROI == "hemisphere") %>%
#   group_by(Sample, Diagnostic) %>%
#   summarise(
#     N = n_distinct(SUBJ),
#     age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
#     age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
#     AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
#     AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
#     AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
#     K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
#     S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
#     I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
#   ) %>% kable(digits = 2) %>% kable_styling()
# 
# 
# filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
#   group_by(Sample, Diagnostic, Gender) %>%
#   summarise(
#     N = n_distinct(SUBJ)
# ) %>% kable(digits = 2) %>% kable_styling()
```

# Results
```{r echo=FALSE}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(y = Age, x = reorder(Sample, Age)), color = "black")+
  geom_boxplot() +
  theme_pubr() + 
  guides(alpha = "none")+ 
  labs(caption = paste("N CTL SUBJ =", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K, alpha = 0.3), color = "black")+
  geom_point(fill = "black", pch = 21, colour = 'white') +
  theme_pubr() + 
  guides(alpha = "none") +
  labs(caption = paste("N CTL SUBJ =", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))) +
  scale_x_continuous(limits = c(0,100))+
  scale_y_continuous()

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K, alpha = 0.3, color = Sample))+
  geom_point() +
  theme_pubr() + 
  guides(alpha = "none") +
  labs(caption = paste("N CTL SUBJ =", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))) +
  scale_x_continuous(limits = c(0,100))+
  scale_y_continuous()

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = S, alpha = 0.3), color = "black")+
  geom_point(fill = "black", pch = 21, colour = 'white') +
  theme_pubr() + 
  guides(alpha = "none") +
  labs(caption = paste("N CTL SUBJ =", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))) +
  scale_x_continuous(limits = c(0,100))+
  scale_y_continuous(limits = c(8,10))

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = S, alpha = 0.3, color = Sample))+
  geom_point() +
  theme_pubr() + 
  guides(alpha = "none") +
  labs(caption = paste("N CTL SUBJ =", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))) +
  scale_x_continuous(limits = c(0,100))+
  scale_y_continuous(limits = c(8,10))

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = I, alpha = 0.3), color = "black")+
  geom_point(fill = "black", pch = 21, colour = 'white') +
  theme_pubr() + 
  guides(alpha = "none") +
  labs(caption = paste("N CTL SUBJ =", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))) +
  scale_x_continuous(limits = c(0,100))+
  scale_y_continuous(limits = c(9.5,11))

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = I, alpha = 0.3, color = Sample))+
  geom_point() +
  theme_pubr() + 
  guides(alpha = "none") +
  labs(caption = paste("N CTL SUBJ =", n_distinct(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))) +
  scale_x_continuous(limits = c(0,100)) +
  scale_y_continuous(limits = c(9.5,11))
```
