---
title: "Malformations"
author: "Fernanda Hansen P. de Moraes"
date: "23/02/2021"
output: 
  html_document: 
    toc: yes
    number_sections: yes
    fig_width: 10
    fig_height: 7
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep_ACC.R")

dados_datasetscomp_PAC017 <- filter(dados_datasetscomp, SUBJ == "PAC017" & Diagnostic == "CCD") # nao tem todos os resultados
dados_datasetscomp_SUBJ069 <- filter(dados_datasetscomp, SUBJ == "SUBJ069" & Diagnostic == "CCD") # nao tem todos os resultados
dados_datasetscomp_SUBJ086 <- filter(dados_datasetscomp, SUBJ == "SUBJ086" & Diagnostic == "CTL" & Sample == "CALTECH") # nao tem todos os resultados

dados_datasetscomp <- dados_datasetscomp %>%
  anti_join(dados_datasetscomp_PAC017) %>%
  anti_join(dados_datasetscomp_SUBJ069) %>%
  anti_join(dados_datasetscomp_SUBJ086) %>%
  filter(!is.na(AvgThickness), !is.na(K), !is.na(logAvgThickness))

# write.csv(dados_datasetscomp,"dados_datasetscomp_malformations.csv")
```

# Datasets description

We included multiple datasets from different sites to estimate, accounting methodological and "subject" biases, typical values for K, S and I.

```{r description, echo=FALSE}
filter(dados_datasetscomp,
       Sample != "Mota&Houzel2015",
       ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
    # ,
    # AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    # AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    # AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    # K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    # S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    # I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()

```

# Cortical folding model by Mota & Houzel (Science, 2015)

Applying the cortical folding from Mota & Houzel:

```{r model, echo=FALSE}

amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness) + log10(TotalArea) ~ log10(ExposedArea), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea), 1 / 2 * log10(AvgThickness) + log10(TotalArea))) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr() 

amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_shiftc) + log10(TotalArea_shiftc) ~ log10(ExposedArea_shiftc), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea_shiftc), 1 / 2 * log10(AvgThickness_shiftc) + log10(TotalArea_shiftc))) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K_shiftc)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr()

amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_age_decay) + log10(TotalArea_age_decay) ~ log10(ExposedArea_age_decay), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea_age_decay), 1 / 2 * log10(AvgThickness_age_decay) + log10(TotalArea_age_decay))) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K_age_decay)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr() 

amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_age_decay_shiftc) + log10(TotalArea_age_decay_shiftc) ~ log10(ExposedArea_age_decay_shiftc), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea_age_decay_shiftc), 1 / 2 * log10(AvgThickness_age_decay_shiftc) + log10(TotalArea_age_decay_shiftc))) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr() 

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K_age_decay_shiftc)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(aes(color = Sample, shape = Diagnostic)) +
  stat_regline_equation() +
  theme_pubr() 
```

# Comparing K values

```{r}

```


## Interhemispheric balance
```{r}
dados_paired <-
  filter(dados_datasetscomp) %>%
  dplyr::select(c(SUBJ, Sample, Diagnostic, hemi, ROI, AvgThickness, K, S, I, logAvgThickness_age_decay_shiftc, K_age_decay_shiftc, S_age_decay_shiftc, I_age_decay_shiftc)) %>%
  pivot_wider(names_from = hemi, values_from = c(AvgThickness, K,S,I, logAvgThickness_age_decay_shiftc, K_age_decay_shiftc, S_age_decay_shiftc, I_age_decay_shiftc)) %>%
  unnest() %>%
  filter(!is.na(K_L) & !is.na(K_R)) %>%
  mutate(delta_T = AvgThickness_L - AvgThickness_R,
         delta_absT = abs(AvgThickness_L - AvgThickness_R),
         delta_K = K_L - K_R,
         delta_absK = abs(K_L - K_R),
         delta_S = S_L - S_R,
         delta_absS = abs(S_L - S_R),
         delta_I = I_L - I_R,
         delta_absI = abs(I_L - I_R),
         delta_T_age_decay_shiftc = logAvgThickness_age_decay_shiftc_L - logAvgThickness_age_decay_shiftc_R,
         delta_absT_age_decay_shiftc = abs(logAvgThickness_age_decay_shiftc_L - logAvgThickness_age_decay_shiftc_R),
         delta_K_age_decay_shiftc = K_age_decay_shiftc_L - K_age_decay_shiftc_R,
         delta_absK_age_decay_shiftc = abs(K_age_decay_shiftc_L - K_age_decay_shiftc_R),
         delta_S_age_decay_shiftc = S_age_decay_shiftc_L - S_age_decay_shiftc_R,
         delta_absS_age_decay_shiftc = abs(S_age_decay_shiftc_L - S_age_decay_shiftc_R),
         delta_I_age_decay_shiftc = I_age_decay_shiftc_L - I_age_decay_shiftc_R,
         delta_absI_age_decay_shiftc = abs(I_age_decay_shiftc_L - I_age_decay_shiftc_R))

dados_paired %>% group_by(Sample, Diagnostic) %>% summarise(N = n_distinct(SUBJ))
```

### K 
```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(Diagnostic, K, color = hemi)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  facet_wrap(Sample ~ .) +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

grouped_ggwithinstats(
  data = dplyr::filter(dados_datasetscomp, ROI == "hemisphere"),
  x = hemi,
  y = K,
  type = "np", # non-parametric statistics
  xlab = "Condition",
  ylab = "Desire to kill an artrhopod",
  grouping.var = Diagnostic,
  outlier.tagging = TRUE,
  outlier.label = SUBJ
)

summary(aov(K ~ hemi*ROI*Sample, dados_datasetscomp))
# TukeyHSD(aov(K ~ hemi*ROI*Sample, dados_datasetscomp))

dados_datasetscomp %>%
  group_by(Sample, Diagnostic, ROI) %>%
  cohens_d(K ~ hemi, paired = TRUE) %>%
  kable() %>% kable_styling()

dados_datasetscomp %>%
  group_by(Sample, Diagnostic, ROI) %>%
  t.test(K ~ hemi, paired = TRUE) %>%
  kable() %>% kable_styling()

ggplot(filter(dados_paired, ROI == "hemisphere"), aes(Diagnostic, delta_absK, color = Sample)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means() +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(Diagnostic, K_age_decay_shiftc, color = hemi)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means(paired = TRUE) +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

grouped_ggbetweenstats(
  data = filter(dados_datasetscomp, ROI == "hemisphere"),
  x = hemi,
  y = K_age_decay_shiftc,
  grouping.var = Diagnostic,
  outlier.tagging = TRUE, 
  outlier.label = SUBJ,
  outlier.coef = 2,
  ggsignif.args = list(textsize = 4, tip_length = 0.01),
  p.adjust.method = "bonferroni",
  ggplot.component = list(ggplot2::scale_y_continuous(sec.axis = ggplot2::dup_axis())),
  palette = "default_jama",
  package = "ggsci",
  plotgrid.args = list(nrow = 1),
  annotation.args = list(title = "Differences in movie length by mpaa ratings for different genres")
)

# summary(aov(dados_paired$delta_K ~ dados_paired$Diagnostic))

dados_datasetscomp %>%
  group_by(Diagnostic, ROI) %>%
  cohens_d(K_age_decay_shiftc ~ hemi, paired = TRUE) %>%
  kable() %>% kable_styling()

ggplot(filter(dados_paired, ROI == "hemisphere"), aes(Diagnostic, delta_absK_age_decay_shiftc)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means() +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### S 
```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(Diagnostic, S, color = hemi)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  facet_wrap(Sample ~ .) +
  stat_compare_means(paired = TRUE) +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# summary(aov(dados_paired$delta_K ~ dados_paired$Diagnostic))

dados_datasetscomp %>%
  group_by(Sample, Diagnostic, ROI) %>%
  cohens_d(S ~ hemi, paired = TRUE) %>%
  kable() %>% kable_styling()

ggplot(filter(dados_paired, ROI == "hemisphere"), aes(Diagnostic, delta_absS, color = Sample)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means() +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(Diagnostic, S_age_decay_shiftc, color = hemi)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means(paired = TRUE) +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

grouped_ggbetweenstats(
  data = filter(dados_datasetscomp, ROI == "hemisphere"),
  x = hemi,
  y = S_age_decay_shiftc,
  grouping.var = Diagnostic,
  outlier.tagging = TRUE, 
  outlier.label = SUBJ,
  outlier.coef = 2,
  ggsignif.args = list(textsize = 4, tip_length = 0.01),
  p.adjust.method = "bonferroni",
  ggplot.component = list(ggplot2::scale_y_continuous(sec.axis = ggplot2::dup_axis())),
  palette = "default_jama",
  package = "ggsci",
  plotgrid.args = list(nrow = 1),
  annotation.args = list(title = "Differences in movie length by mpaa ratings for different genres")
)

# summary(aov(dados_paired$delta_K ~ dados_paired$Diagnostic))

dados_datasetscomp %>%
  group_by(Diagnostic, ROI) %>%
  cohens_d(S_age_decay_shiftc ~ hemi, paired = TRUE) %>%
  kable() %>% kable_styling()

ggplot(filter(dados_paired, ROI == "hemisphere"), aes(Diagnostic, delta_absS_age_decay_shiftc)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means() +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


### I
```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(Diagnostic, I, color = hemi)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  facet_wrap(Sample ~ .) +
  stat_compare_means(paired = TRUE) +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# summary(aov(dados_paired$delta_K ~ dados_paired$Diagnostic))

dados_datasetscomp %>%
  group_by(Sample, Diagnostic, ROI) %>%
  cohens_d(I ~ hemi, paired = TRUE) %>%
  kable() %>% kable_styling()

ggplot(filter(dados_paired, ROI == "hemisphere"), aes(Diagnostic, delta_absI, color = Sample)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means() +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere"), aes(Diagnostic, I_age_decay_shiftc, color = hemi)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means(paired = TRUE) +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

grouped_ggbetweenstats(
  data = filter(dados_datasetscomp, ROI == "hemisphere"),
  x = hemi,
  y = I_age_decay_shiftc,
  grouping.var = Diagnostic,
  outlier.tagging = TRUE, 
  outlier.label = SUBJ,
  outlier.coef = 2,
  ggsignif.args = list(textsize = 4, tip_length = 0.01),
  p.adjust.method = "bonferroni",
  ggplot.component = list(ggplot2::scale_y_continuous(sec.axis = ggplot2::dup_axis())),
  palette = "default_jama",
  package = "ggsci",
  plotgrid.args = list(nrow = 1),
  annotation.args = list(title = "Differences in movie length by mpaa ratings for different genres")
)

# summary(aov(dados_paired$delta_K ~ dados_paired$Diagnostic))

dados_datasetscomp %>%
  group_by(Diagnostic, ROI) %>%
  cohens_d(I_age_decay_shiftc ~ hemi, paired = TRUE) %>%
  kable() %>% kable_styling()

ggplot(filter(dados_paired, ROI == "hemisphere"), aes(Diagnostic, delta_absI_age_decay_shiftc)) +
  geom_boxplot() +
  geom_jitter(aes(alpha = 0.2)) +
  stat_compare_means() +
  theme_pubr() +
  guides(alpha = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```