---
title: "Malformations"
author: "Fernanda Hansen P. de Moraes"
date: "23/02/2021"
output: 
  html_document: 
    toc: yes
    number_sections: yes
    fig_width: 10
    fig_height: 7
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      cache = TRUE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 0

# Prepara os dados para analise
source("05-analises_prep_ALL.R")

dados_datasetscomp_PAC017 <- filter(dados_datasetscomp, SUBJ == "PAC017" & Diagnostic == "CCD") # nao tem todos os resultados
dados_datasetscomp_SUBJ069 <- filter(dados_datasetscomp, SUBJ == "SUBJ069" & Diagnostic == "CCD") # nao tem todos os resultados
dados_datasetscomp_SUBJ086 <- filter(dados_datasetscomp, SUBJ == "SUBJ086" & Diagnostic == "CTL" & Sample == "CALTECH") # nao tem todos os resultados

dados_datasetscomp_ALL <- dados_datasetscomp %>%
  filter(!is.na(AvgThickness),
         !is.na(K),
         !is.na(logAvgThickness),
         !is.na(Diagnostic),
         Sample == "AOMICPIOP1" | Sample == "AHEAD" | Sample == "ADNI" | Sample == "HCPr900" | Sample == "NKI" | Sample == "IDOR")

dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "IDOR"] <- "IDOR-ADproj"


dados_datasetscomp <- dados_datasetscomp %>%
  anti_join(dados_datasetscomp_PAC017) %>%
  anti_join(dados_datasetscomp_SUBJ069) %>%
  anti_join(dados_datasetscomp_SUBJ086) %>%
  filter(!is.na(AvgThickness),
         !is.na(K),
         !is.na(logAvgThickness),
         Sample == "IDOR-CCD" | Sample == "UCSF" | Sample == "CALTECH" | Sample == "IDOR-ZK" | Sample == "IDOR-MICRO" | Sample == "Mota&Houzel2015",
         Diagnostic == "CTL" | Diagnostic == "CCD" | Diagnostic == "ZK")

# write.csv(dados_datasetscomp,"dados_datasetscomp_malformations.csv")
```

```{r}
# nao podemos harmonizar os dados da zika por nao ter controles -> podemos assumir algum erro baseado no outro estudo para aumentar a incerteza quando comparar o alpha, K, S e I de outras amostras?

dados_datasetscomp <- dados_datasetscomp %>%
  mutate(
    AvgThickness_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",AvgThickness,AvgThickness_shiftc),
    TotalArea_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",TotalArea,TotalArea_shiftc),
    ExposedArea_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",ExposedArea,ExposedArea_shiftc),
    localGI_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",TotalArea/ExposedArea,TotalArea_shiftc/ExposedArea_shiftc),
    K_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",log10(TotalArea) + 1/4*log10(AvgThickness^2) - 5/4*log10(ExposedArea), log10(TotalArea_shiftc) + 1/4*log10(AvgThickness_shiftc^2) - 5/4*log10(ExposedArea_shiftc)),
    I_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO", log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2), log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2)),
    S_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO", 3/2*log10(TotalArea) + 3/4*log10(ExposedArea) - 9/4*log10(AvgThickness^2), 3/2*log10(TotalArea_shiftc) + 3/4*log10(ExposedArea_shiftc) - 9/4*log10(AvgThickness_shiftc^2)),
    Knorm_shiftc = K_shiftc / sqrt(1 + (1 / 4) ^ 2 + (5 / 2) ^ 2),
    Snorm_shiftc = S_shiftc / sqrt((3 / 2) ^ 2 + (3 / 4) ^ 2 + (9 / 4) ^ 2),
    Inorm_shiftc = I_shiftc / sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 2)
  )

```

# Datasets description

We included multiple datasets from different sites to estimate, accounting methodological and "subject" biases, typical values for K, S and I.

```{r description, echo=FALSE}
filter(dados_datasetscomp,
       Sample != "Mota&Houzel2015",
       ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
    # ,
    # AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    # AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    # AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    # K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    # S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    # I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(y = Age, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal()
```

## ZIKA description
```{r}
filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "ZK") %>%
  dplyr::select(c(SUBJ, Age, Gender,Origem)) %>%
  unique() %>%
  kable() %>% kable_styling()
```

# Cortical folding model by Mota & Houzel (Science, 2015)

Applying the cortical folding from Mota & Houzel:

```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef

ggplot(filter(filter(dados_datasetscomp, ROI == "hemisphere")), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness))) +
  geom_point(aes(color = Family)) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm", color = "#336600", fill = "#336600") +
  stat_regline_equation()
```

```{r}

dados_datasetscomp$Sample[dados_datasetscomp$Sample == "IDOR-CCD"] <- "IDOR"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "IDOR-ZK"] <- "IDOR"

dados_datasetscomp$Diagnostic <- factor(dados_datasetscomp$Diagnostic, levels = c("CTL", "CCD", "ZK"))

amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  do(fit_amostra = tidy(lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

amostra_Coef_N <- filter(dados_datasetscomp_ALL, ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(N= n_distinct(SUBJ))

amostra_Coef <- full_join(amostra_Coef, amostra_Coef_N)

a <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness), color = Diagnostic, fill = Diagnostic)) +
  geom_point(aes(shape = Sample)) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm") +
    theme(axis.text.x = element_text(size = 11),
          axis.text.y = element_text(size = 11)) +
  stat_regline_equation()

b <- ggplot(filter(amostra_Coef, term == "log10(ExposedArea)"), aes(x = Sample, y = estimate, ymin = conf.low, ymax = conf.high, shape = Diagnostic)) +
  geom_point(position="dodge") +
  geom_errorbar(position="dodge") +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  stat_regline_equation() +
  facet_wrap(Diagnostic ~., scales = "free_x") +
  theme_minimal() +
  labs(y = "Slope alpha") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 11),
        axis.text.y = element_text(size = 12)) +
 # geom_label(aes(label = N), nudge_y = 0.3) +
  labs(caption = "Bars representing confidence interval.")

fig <- ggarrange(a, b,labels = c("A","B"), nrow = 1, ncol = 2, font.label = list(size = 12), common.legend = TRUE, legend = "bottom")

fig_1 <- annotate_figure(fig,
                top = text_grob("Universal Cortical folding model application to harmonized variables", face = "bold", size = 14),
                bottom = text_grob(wrapper("Fig 1. All samples follow the universal rule (A), assessed by the slope alpha (B), which theoretical value (1.25, dashed line) should be comprised in the confidence interval of each regression. To compare with the original publication, we included the experimental results for the mammal included in (Mota e Herculano-Houzel 2015).", width = 125), face = "italic", size = 13))

ggsave("OHBM_fig1.png", plot = fig_1, dpi=100, width = 1000, height = 763, units = "px", device = "png")

fig <- annotate_figure(fig,
                top = text_grob("Universal Cortical folding model application to harmonized variables", face = "bold", size = 14))

ggsave("OHBM_fig1_nocaption.png", plot = fig, dpi=100, width = 1000, height = 763, units = "px", device = "png")

```


```{r}
dados_datasetscomp_ALL <- full_join(dados_datasetscomp, dados_datasetscomp_ALL)
write.csv(dados_datasetscomp_ALL, "dados_datasetscomp_ALL.csv")

dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "ADNI"] <- "Wang2019"
dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "HCPr900"] <- "Wang2019"
dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "NKI"] <- "Wang2019"
dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "OASIS"] <- "Wang2019"

dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "AOMICPIOP1"] <- "deMoraes2021"
dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "AOMICPIOP2"] <- "deMoraes2021"
dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "AHEAD"] <- "deMoraes2021"
dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "IDOR-ADproj"] <- "deMoraes2021"

dados_datasetscomp_ALL$Diagnostic <- factor(dados_datasetscomp_ALL$Diagnostic, levels = c("CTL", "CCD", "ZK", "AD"))

dados_datasetscomp_ALL <- filter(dados_datasetscomp_ALL, !is.na(ExposedArea_shiftc), !is.na(AvgThickness_shiftc), !is.na(TotalArea_shiftc),  !is.na(Diagnostic))

amostra_Coef <- filter(dados_datasetscomp_ALL, ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  do(fit_amostra = tidy(lm(log10(TotalArea_shiftc*sqrt(AvgThickness_shiftc)) ~ log10(ExposedArea_shiftc), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

amostra_Coef_N <- filter(dados_datasetscomp_ALL, ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(N= n_distinct(SUBJ))

# amostra_Coef_N

amostra_Coef <- full_join(amostra_Coef, amostra_Coef_N)

ggplot(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Family == "Hominidae"), aes(x = ExposedArea_shiftc, y = TotalArea_shiftc*sqrt(AvgThickness_shiftc))) +
  geom_point(aes(color = Diagnostic)) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm", color = "black", fill = "black", alpha = 0.4) +
  stat_regline_equation()

a <- ggplot(filter(dados_datasetscomp_ALL , ROI == "hemisphere", Family == "Hominidae"), aes(x = ExposedArea_shiftc, y = TotalArea_shiftc*sqrt(AvgThickness_shiftc), color = Diagnostic, fill = Diagnostic)) +
  geom_point(aes(shape = Sample)) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm") +
  stat_regline_equation()

b <- ggplot(filter(amostra_Coef, term == "log10(ExposedArea_shiftc)"), aes(x = Sample, y = estimate, ymin = conf.low, ymax = conf.high, shape = Diagnostic)) +
  geom_point() +
  geom_errorbar() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  stat_regline_equation() +
  facet_wrap(Diagnostic ~., scales = "free_x") +
  theme_minimal() +
  labs(y = "Slope alpha") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_label(aes(label = N), nudge_y = 0.3)

fig <- ggarrange(a, b,labels = c("A","B"), nrow = 1, ncol = 2, font.label = list(size = 11), common.legend = TRUE, legend = "bottom")

annotate_figure(fig, top = text_grob("Universal Cortical folding model application to harmonized variables"))
```

```{r}
ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(y = k, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal()

figa <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae", Diagnostic != "ZK"), aes(y = K, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal() + 
  stat_compare_means(method = "t.test")

aov <- aov(K ~ Diagnostic*Sample, filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae", Diagnostic != "ZK"))
TukeyHSD(aov)

figb <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae", Diagnostic != "ZK"), aes(y = S, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal() + 
  stat_compare_means(method = "t.test")

aov <- aov(S ~ Diagnostic*Sample, filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae", Diagnostic != "ZK"))
TukeyHSD(aov)

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(y = I, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal()+ 
  stat_compare_means(method = "t.test")

ggarrange(ggarrange(figa, figb, labels = c("A","B"), nrow = 1, ncol = 3, font.label = list(size = 11), common.legend = TRUE, legend = "top"))

```

```{r}
a <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(y = K, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal()

b <-ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(y = S, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal() 

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(y = I, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal()

ggarrange(ggarrange(a, b,labels = c("A","B"), nrow = 1, ncol = 2, font.label = list(size = 11), common.legend = TRUE, legend = "top"))
```

## ZIKA vs Simulados CTL

```{r}
# amostra_Coef <- lm(log10(TotalArea *sqrt(AvgThickness)) ~ log10(ExposedArea), data = filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL", Age < 30), na.action = na.omit)
# alpha <- as.data.frame(tidy(amostra_Coef)[2,2])$estimate
# alpha_sd <- as.data.frame(tidy(amostra_Coef)[2,3])$std.error
# k <- as.data.frame(tidy(amostra_Coef)[1,2])$estimate
# k_sd <- as.data.frame(tidy(amostra_Coef)[1,3])$std.error

cov <- filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL", Age < 30) %>%
  dplyr::select(c(Age, AvgThickness, TotalArea, ExposedArea)) %>%
  cov()

mean <- c(mean(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "ZK", Age < 30)$Age), mean(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL", Age < 30)$AvgThickness), mean(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL", Age < 30)$TotalArea), mean(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL", Age < 30)$ExposedArea))

simulated_values <-
  as.data.frame(mvrnorm(n = 10000, mu = mean, Sigma = cov, empirical = TRUE)) %>%
  mutate(
    Diagnostic = "CTL",
    ROI = "hemisphere",
    Sample = "predicted",
    Family = "Hominidae",
    Species = "Homo sapiens"
  ) %>%
  filter(
    Age > floor(min(
      filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "ZK")$Age
    ))&
      Age < ceiling(max(
        filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "ZK")$Age
      ))
  )
```

#### Teste se os valores simulados cabem no modelo
```{r eval=FALSE, include=FALSE}
# ggplot(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL", Age <30), aes(x=ExposedArea, y =TotalArea*sqrt(AvgThickness))) +
#   geom_point(aes(alpha = 0.3)) +
#   geom_abline(slope = alpha, intercept = k)+
#   geom_abline(slope = alpha-alpha_sd, intercept = k-k_sd, linetype = "dashed") +
#   geom_abline(slope = alpha+alpha_sd, intercept = k+k_sd, linetype = "dashed") + 
#   scale_x_log10()+
#   scale_y_log10()+
#   guides(alpha = "none") +
#   theme_minimal()

ggplot(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL", Age <30), aes(x=ExposedArea, y =TotalArea*sqrt(AvgThickness))) +
  geom_point(aes(alpha = 0.3)) + 
  geom_abline(slope = alpha, intercept = k)+
  geom_abline(slope = alpha-alpha_sd, intercept = k-k_sd, linetype = "dashed") +
  geom_abline(slope = alpha+alpha_sd, intercept = k+k_sd, linetype = "dashed") +
  geom_point(data = simulated_values, aes(x=ExposedArea, y =TotalArea*sqrt(AvgThickness), alpha = 0.3), color = "red") + 
  scale_x_log10()+
  scale_y_log10()+
  guides(alpha = "none") +
  theme_minimal()

```

### K, S and I

```{r}
simulated_values <- simulated_values %>% mutate(
  localGI = TotalArea / ExposedArea,
  k = sqrt(AvgThickness) * TotalArea / (ExposedArea ^ 1.25),
  K = 1 / 4 * log10(AvgThickness^2)  + log10(TotalArea) - 5 / 4 * log10(ExposedArea),
  S = 3 / 2 * log10(TotalArea) + 3 / 4 * log10(ExposedArea) - 9 /  4 * log10(AvgThickness^2),
  I = log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2)
)

dados_datasetscomp_ALL_pred <- full_join(dados_datasetscomp_ALL, simulated_values)
```

```{r}
ggplot(filter(dados_datasetscomp_ALL_pred, ROI == "hemisphere", Family == "Hominidae"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness))) +
  geom_point(aes(color = Sample)) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm", color = "black", fill = "black", alpha = 0.4) +
  stat_regline_equation()

```

```{r}
simulated_values$Diagnostic <- "CTL-simulated"
paste("N dados simulados = ", n_distinct(simulated_values))
dados_datasetscomp_pred <- full_join(dados_datasetscomp, simulated_values)

dados_datasetscomp_pred$Diagnostic <- factor(dados_datasetscomp_pred$Diagnostic, levels = c("CTL", "CTL-simulated", "CCD", "ZK"))

amostra_Coef <- filter(dados_datasetscomp_pred, ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  do(fit_amostra = tidy(lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

amostra_Coef_N <- filter(dados_datasetscomp_ALL, ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(N= n_distinct(SUBJ))

# amostra_Coef_N

amostra_Coef <- full_join(amostra_Coef, amostra_Coef_N)

a <- ggplot(filter(dados_datasetscomp_pred, ROI == "hemisphere", Family == "Hominidae"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness), color = Diagnostic, fill = Diagnostic)) +
  geom_point(aes(shape = Sample, alpha = ifelse(Diagnostic == "CTL-simulated", 0.1, 0.3))) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area", y = "sqrt(AvgThickness)* Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm") +
  guides(alpha = "none") +
  stat_regline_equation()
a

b <- ggplot(filter(amostra_Coef, term == "log10(ExposedArea)"), aes(x = Sample, y = estimate, ymin = conf.low, ymax = conf.high, shape = Diagnostic)) +
  geom_point(position="dodge") +
  geom_errorbar(position="dodge") +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  stat_regline_equation() +
  facet_wrap(Diagnostic ~., scales = "free_x") +
  theme_minimal() +
  labs(y = "Slope alpha") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_label(aes(label = N), nudge_y = 0.3) +
  labs(caption = "Number of subject indicated on top of each confidence interval bar.")
b

fig <- ggarrange(a, b,labels = c("A","B"), nrow = 1, ncol = 2, font.label = list(size = 11), common.legend = TRUE, legend = "bottom")

annotate_figure(fig, top = text_grob("Universal Cortical folding model application to harmonized variables"))
```

```{r}

dados_datasetscomp_ZK <- filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae", Diagnostic == "ZK") %>%
  full_join(simulated_values) %>%
  mutate(Sample = "ZIKA")

figc <- ggplot(dados_datasetscomp_ZK, aes(y = K, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal() + 
  stat_compare_means(method = "t.test")

figd <- ggplot(dados_datasetscomp_ZK, aes(y = S, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal() + 
  stat_compare_means(method = "t.test")

ggplot(dados_datasetscomp_ZK, aes(y = I, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  guides(alpha = "none") +
  theme_minimal() + 
  stat_compare_means(method = "t.test")

figab <- ggarrange(figa, figb, labels = c("A","B"), nrow = 1, ncol = 2, font.label = list(size = 11), common.legend = TRUE, legend = "top")
figcd <- ggarrange(figc, figd, labels = c("C","D"), nrow = 1, ncol = 2, font.label = list(size = 11), common.legend = TRUE, legend = "top")
fig2 <- ggarrange(figab, figcd,nrow = 2, ncol = 1)

fig2_2 <- annotate_figure(fig2,
                       top = text_grob("Differences in independent cortical folding variables", face = "bold", size = 14),
                       bottom = text_grob(wrapper("Fig 2. Comparing K and S for CCD and healthy controls (A and B) and ZIKA+ versus simulated controls (C and D). There are significant differences in K and S for both comparisons. In A and B, all CCD samples present lower values of K and S in comparison to controls, despite the not significant difference, probably due to the heterogeneous atrophy severity in the samples. In (C and D), ZIKA+ subjects present higher K values, not noticed before in the previously studied pathologies. However, S values are shallow, even for the Control subjects in the CCD comparisons, indicating a non-typical brain shape.", width = 125), face = "italic", size = 13)
)

ggsave("OHBM_fig2.png", plot = fig2_2, dpi=100, width = 1000, height = 763, units = "px", device = "png")

fig2 <- annotate_figure(fig2,
                       top = text_grob("Differences in independent cortical folding variables", face = "bold", size = 14)
)

ggsave("OHBM_fig2_nocaption.png", plot = fig2, dpi=100, width = 1000, height = 763, units = "px", device = "png")

```
