---
title: "Malformations"
author: "Fernanda Hansen P. de Moraes"
date: "23/02/2021"
output: 
  html_document: 
    toc: yes
    number_sections: yes
    fig_width: 10
    fig_height: 7
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      cache = TRUE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 0

# Prepara os dados para analise
source("05-analises_prep_ALL.R")

dados_datasetscomp_PAC017 <- filter(dados_datasetscomp, SUBJ == "PAC017" & Diagnostic == "CCD") # nao tem todos os resultados
dados_datasetscomp_SUBJ069 <- filter(dados_datasetscomp, SUBJ == "SUBJ069" & Diagnostic == "CCD") # nao tem todos os resultados
dados_datasetscomp_SUBJ086 <- filter(dados_datasetscomp, SUBJ == "SUBJ086" & Diagnostic == "CTL" & Sample == "CALTECH") # nao tem todos os resultados

dados_datasetscomp_ALL <- dados_datasetscomp %>%
  filter(!is.na(AvgThickness),
         !is.na(K),
         !is.na(logAvgThickness),
         !is.na(Diagnostic),
         Sample == "AOMICPIOP1" | Sample == "AHEAD" | Sample == "ADNI" | Sample == "HCPr900" | Sample == "NKI" | Sample == "IDOR")

# | Sample == "OASIS" -> não foi incluido no estudo de 2019

dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "IDOR"] <- "IDOR-ADproj"


dados_datasetscomp <- dados_datasetscomp %>%
  anti_join(dados_datasetscomp_PAC017) %>%
  anti_join(dados_datasetscomp_SUBJ069) %>%
  anti_join(dados_datasetscomp_SUBJ086) %>%
  filter(!is.na(AvgThickness),
         !is.na(K),
         !is.na(logAvgThickness),
         Sample == "IDOR-CCD" | Sample == "UCSF" | Sample == "CALTECH" | Sample == "IDOR-ZK" | Sample == "IDOR-MICRO" | Sample == "Mota&Houzel2015",
         Diagnostic == "CTL" | Diagnostic == "CCD" | Diagnostic == "ZK")

# write.csv(dados_datasetscomp,"dados_datasetscomp_malformations.csv")

set.seed(1)

library("Runuran")

```

```{r}
# nao podemos harmonizar os dados da zika por nao ter controles -> podemos assumir algum erro baseado no outro estudo para aumentar a incerteza quando comparar o alpha, K, S e I de outras amostras?

dados_datasetscomp <- dados_datasetscomp %>%
  mutate(
    AvgThickness_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",AvgThickness,AvgThickness_shiftc),
    TotalArea_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",TotalArea,TotalArea_shiftc),
    ExposedArea_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",ExposedArea,ExposedArea_shiftc),
    localGI_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",TotalArea/ExposedArea,TotalArea_shiftc/ExposedArea_shiftc),
    K_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO",log10(TotalArea) + 1/4*log10(AvgThickness^2) - 5/4*log10(ExposedArea), log10(TotalArea_shiftc) + 1/4*log10(AvgThickness_shiftc^2) - 5/4*log10(ExposedArea_shiftc)),
    I_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO", log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2), log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2)),
    S_shiftc = ifelse(Sample == "IDOR-ZK" | Sample == "IDOR-MICRO", 3/2*log10(TotalArea) + 3/4*log10(ExposedArea) - 9/4*log10(AvgThickness^2), 3/2*log10(TotalArea_shiftc) + 3/4*log10(ExposedArea_shiftc) - 9/4*log10(AvgThickness_shiftc^2)),
    Knorm_shiftc = K_shiftc / sqrt(1 + (1 / 4) ^ 2 + (5 / 2) ^ 2),
    Snorm_shiftc = S_shiftc / sqrt((3 / 2) ^ 2 + (3 / 4) ^ 2 + (9 / 4) ^ 2),
    Inorm_shiftc = I_shiftc / sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 2)
  )

```

# Datasets description

We included multiple datasets from different sites to estimate, accounting methodological and "subject" biases, typical values for K, S and I.

```{r description, echo=FALSE}
filter(dados_datasetscomp_ALL,
       Sample != "Mota&Houzel2015",
       ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
    # ,
    # AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    # AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    # AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    # K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    # S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    # I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Family == "Hominidae"), aes(y = Age, x = Sample, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot()+
  theme_minimal()
```

```{r}

dados_datasetscomp$Sample[dados_datasetscomp$Sample == "IDOR-CCD"] <- "IDOR"
dados_datasetscomp$Sample[dados_datasetscomp$Sample == "IDOR-ZK"] <- "IDOR"

dados_datasetscomp$Diagnostic <- factor(dados_datasetscomp$Diagnostic, levels = c("CTL", "CCD", "ZK"))
```


```{r}
dados_datasetscomp_ALL <- full_join(dados_datasetscomp, dados_datasetscomp_ALL)
# dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "ADNI"] <- "Wang2019"
# dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "HCPr900"] <- "Wang2019"
# dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "NKI"] <- "Wang2019"
# dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "OASIS"] <- "Wang2019"
# 
# dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "AOMICPIOP1"] <- "deMoraes2021"
# dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "AHEAD"] <- "deMoraes2021"
# dados_datasetscomp_ALL$Sample[dados_datasetscomp_ALL$Sample == "IDOR-ADproj"] <- "deMoraes2021"

dados_datasetscomp_ALL$Diagnostic <- factor(dados_datasetscomp_ALL$Diagnostic, levels = c("CTL", "CCD", "ZK", "AD"))

dados_datasetscomp_ALL <- filter(dados_datasetscomp_ALL, !is.na(ExposedArea_shiftc), !is.na(AvgThickness_shiftc), !is.na(TotalArea_shiftc),  !is.na(Diagnostic), !is.na(ExposedArea), !is.na(AvgThickness), !is.na(TotalArea))

```

## ZIKA vs Simulados CTL

```{r}
# Age <- as_tibble(rnorm(10000, mean = mean(dados_datasetscomp_ALL$Age), sd = sd(dados_datasetscomp_ALL$Age)))
# Age <- as_tibble(runif(10000, min = min(dados_datasetscomp_ALL$Age), max = max(dados_datasetscomp_ALL$Age)))
Age <- as_tibble(urnorm(n = 10000, mean = mean(dados_datasetscomp_ALL$Age), sd = sd(dados_datasetscomp_ALL$Age), lb = min(dados_datasetscomp_ALL$Age), ub = max(dados_datasetscomp_ALL$Age)))
colnames(Age)[1] <- "Age"
```

### AvgThickness
```{r}
ggplot(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"), aes(Age, AvgThickness, color = Sample, fill = Sample)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

m.0 <- lm(AvgThickness ~ Age , data = filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"))
m.1 <- lme4::lmer(AvgThickness ~ Age + (1|Sample) , data = filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"))

sum <- summary(m.1)
# fixed <- as_tibble(fixef(m.1))
# random <- as_tibble(ranef(m.1))
# confint.merMod(m.1)

b <- fixef(m.1)[1] ## intercept
a <- fixef(m.1)[2] ## slope
sd.b <- sqrt(unlist(VarCorr(m.1))) ## random effects SD
# sd.b <- sum$sigma
sd.a <- sum$coefficients[2,2] ## slope sd

pred <- Age %>% mutate(
  Age = Age,
  # AvgThickness = rnorm(10000, mean = a * Age + b, sd = sqrt((abs(Age) * sd.a) ^ 2 + sd.b ^2)),
  AvgThickness = urnorm(n = 10000, mean = a * Age + b, sd = sqrt((abs(Age) * sd.a) ^ 2 + sd.b ^2), lb = min(dados_datasetscomp_ALL$AvgThickness), ub = max(dados_datasetscomp_ALL$AvgThickness)),
  Diagnostic = "CTL",
  ROI = "hemisphere",
  Sample = "predicted",
  Family = "Hominidae",
  Species = "Homo sapiens"
)

ggplot(pred, aes(Age, AvgThickness)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()
```

### Total Area
```{r}
ggplot(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"), aes(Age, TotalArea, color = Sample, fill = Sample)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

ggplot(dados_datasetscomp_ALL, aes(x = Sample, y = TotalArea)) +
  geom_boxplot() +
  theme_minimal()

m.0 <- lm(TotalArea ~ Age , data = filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"))
m.1 <- lme4::lmer(TotalArea ~ Age + (1|Sample) , data = filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"))

sum <- summary(m.1)
# fixed <- as_tibble(fixef(m.1))
# random <- as_tibble(ranef(m.1))
# confint.merMod(m.1)

b <- fixef(m.1)[1] ## intercept
a <- fixef(m.1)[2] ## slope
sd.b <- sqrt(unlist(VarCorr(m.1))) ## random effects SD
# sd.b <- sum$sigma
sd.a <- sum$coefficients[2,2] ## slope sd

pred <- pred %>% mutate(
  # TotalArea = rnorm(10000, mean = a * Age + b, sd = sqrt((abs(Age) * sd.a) ^ 2 + sd.b ^2)),
  TotalArea = urnorm(n = 10000, mean = a * Age + b, sd = sqrt((abs(Age) * sd.a) ^ 2 + sd.b ^2), lb = min(dados_datasetscomp_ALL$TotalArea), ub = max(dados_datasetscomp_ALL$TotalArea))
)

ggplot(pred, aes(Age, TotalArea, color = Sample, fill = Sample)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()
```

### Exposed Area
```{r}
ggplot(filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"), aes(Age, ExposedArea, color = Sample, fill = Sample)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

m.0 <- lm(ExposedArea ~ Age , data = filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"))
m.1 <- lme4::lmer(ExposedArea ~ Age + (1|Sample) , data = filter(dados_datasetscomp_ALL, ROI == "hemisphere", Diagnostic == "CTL"))

sum <- summary(m.1)
# fixed <- as_tibble(fixef(m.1))
# random <- as_tibble(ranef(m.1))
# confint.merMod(m.1)

b <- fixef(m.1)[1] ## intercept
a <- fixef(m.1)[2] ## slope
sd.b <- sqrt(unlist(VarCorr(m.1))) ## random effects SD
# sd.b <- sum$sigma
sd.a <- sum$coefficients[2,2] ## slope sd

pred <- pred %>% mutate(
 # ExposedArea = c(10000, mean = a * Age + b, sd = sqrt((abs(Age) * sd.a) ^ 2 + sd.b ^2))),
  ExposedArea = urnorm(n = 10000, mean = a * Age + b, sd = sqrt((abs(Age) * sd.a) ^ 2 + sd.b ^2), lb = min(dados_datasetscomp_ALL$ExposedArea), ub = max(dados_datasetscomp_ALL$ExposedArea)))

ggplot(pred, aes(Age, ExposedArea, color = Sample, fill = Sample)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

```

### K, S and I

```{r}
pred <- pred %>% mutate(
  localGI = TotalArea / ExposedArea,
  k = sqrt(AvgThickness) * TotalArea / (ExposedArea ^ 1.25),
  K = 1 / 4 * log10(AvgThickness^2)  + log10(TotalArea) - 5 / 4 * log10(ExposedArea),
  S = 3 / 2 * log10(TotalArea) + 3 / 4 * log10(ExposedArea) - 9 /  4 * log10(AvgThickness^2),
  I = log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2)
)

dados_datasetscomp_ALL_pred <- full_join(dados_datasetscomp_ALL, pred)
```

```{r}
ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(x = Sample, y = Age)) +
  geom_boxplot() +
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(x = Sample, y = AvgThickness)) +
  geom_boxplot() +
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(Age, AvgThickness)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(x = Sample, y = TotalArea)) +
  geom_boxplot() +
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(Age, TotalArea)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(x = Sample, y = ExposedArea)) +
  geom_boxplot() +
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(Age, ExposedArea)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()


ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(x = Sample, y = K)) +
  geom_boxplot() +
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(Age, K)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(x = Sample, y = S)) +
  geom_boxplot() +
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(Age, S)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(x = Sample, y = I)) +
  geom_boxplot() +
  theme_minimal()

ggplot(filter(dados_datasetscomp_ALL_pred, Diagnostic == "CTL", ROI == "hemisphere"), aes(Age, I)) +
  geom_point(aes(color = Sample)) +
  geom_smooth(method = "lm") +
  stat_regline_equation()+
  theme_minimal()

```


```{r}

# dados_datasetscomp_ALL <- filter(dados_datasetscomp_ALL, !is.na(Diagnostic), !is.na(ExposedArea), !is.na(AvgThickness), !is.na(TotalArea))

amostra_Coef <- filter(dados_datasetscomp_ALL_pred, ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  do(fit_amostra = tidy(lm(log10(TotalArea*sqrt(AvgThickness)) ~ log10(ExposedArea), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)
amostra_Coef %>% kable(digits = 2) %>% kable_styling()

ggplot(filter(dados_datasetscomp_ALL_pred, ROI == "hemisphere", Family == "Hominidae"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness))) +
  geom_point(aes(color = Sample)) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm", color = "black", fill = "black", alpha = 0.4) +
  stat_regline_equation()

a <- ggplot(filter(dados_datasetscomp_ALL_pred, ROI == "hemisphere", Family == "Hominidae"), aes(x = ExposedArea, y = TotalArea*sqrt(AvgThickness), color = Diagnostic, fill = Diagnostic)) +
  geom_point(aes(shape = Sample)) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Exposed cortical surface area (mm²)", y = "sqrt(AvgThickness) * Total cortical surface area") +
  theme_minimal() +
  stat_smooth(method = "lm") +
  stat_regline_equation()
a

b <- ggplot(filter(amostra_Coef, term == "log10(ExposedArea)"), aes(x = Sample, y = estimate, ymin = conf.low, ymax = conf.high, shape = Diagnostic)) +
  geom_point(position="dodge") +
  geom_errorbar(position="dodge") +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
  stat_regline_equation() +
  facet_wrap(Diagnostic ~., scales = "free_x") +
  theme_minimal() +
  labs(y = "Slope alpha") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
b

fig <- ggarrange(a, b,labels = c("A","B"), nrow = 1, ncol = 2, font.label = list(size = 11), common.legend = TRUE, legend = "bottom")

annotate_figure(fig, top = text_grob("Universal Cortical folding model application to harmonized variables"))
```