---
title: "T1 vs T1+T2"
author: "Fernanda Hansen P. de Moraes"
date: "02/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep_t1t2.R")

# write.csv(dados_datasetscomp,"dados_datasetscomp_malformations.csv")
```

# comparing T1 e T1+T2 for sub-SUBJ037
```{r eval=FALSE, include=FALSE}
# dados_zk_037_comp <- filter(dados_zk_037_comp, !is.na(Hemisphere))

dados_zk_037_comp_wide_T1 <- dados_zk_037_comp %>%
  dplyr::select(-c(Lobe, PCRZIKA, Gender, Diagnostic)) %>%
  pivot_longer(!c(SUBJ, Hemisphere, ROI, FS), names_to = "measure", values_to = "value") %>%
  pivot_wider(names_from = FS, values_from = value) %>%
  dplyr::select(-c(T1T2)) %>%
  filter(!is.na(T1)) %>%
  unnest(T1)

dados_zk_037_comp_wide_T2 <- dados_zk_037_comp %>%
  dplyr::select(-c(Lobe, PCRZIKA, Gender, Diagnostic)) %>%
  pivot_longer(!c(SUBJ, Hemisphere, ROI, FS), names_to = "measure", values_to = "value") %>%
  pivot_wider(names_from = FS, values_from = value) %>%
  dplyr::select(-c(T1)) %>%
  filter(!is.na(T1T2)) %>%
  unnest(T1T2)

dados_zk_037_comp_wide <- full_join(dados_zk_037_comp_wide_T1, dados_zk_037_comp_wide_T2) %>%
  mutate(diff = T1 - T1T2)

ggplot(data = dados_zk_037_comp_wide, aes(x = T1, y = T1T2, color = Hemisphere)) +
  geom_point() +
  stat_cor() +
  theme_pubr()

ggplot(data = filter(dados_zk_037_comp_wide, diff > 0), aes(x = T1, y = T1T2, color = Hemisphere)) +
  geom_point() +
  stat_cor() +
  theme_pubr()

ggplot(data = dados_zk_037_comp_wide, aes(x = diff, color = Hemisphere, fill = Hemisphere, alpha = 0.4)) +
  geom_histogram() +
  guides(alpha = FALSE) +
  theme_pubr()

ggplot(data = filter(dados_zk_037_comp_wide, diff > 0), aes(x = measure, y = diff, color = Hemisphere)) +
    geom_point() +
    theme_pubr() +
  facet_wrap(ROI ~. ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

ggplot(data = filter(dados_zk_037_comp_wide, diff > 0), aes(x = measure, y = diff/T1, color = Hemisphere)) +
    geom_point() +
    theme_pubr() +
  facet_wrap(ROI ~. ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

```