---
title: "Typical"
author: "Fernanda Hansen P. de Moraes"
date: "05/03/2021"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(cache=TRUE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep.R")

dados_datasetscomp <- dados_datasetscomp %>% filter(Sample != "HCP500r")

# dados_datasetscomp <- dados_datasetscomp %>% filter(Age == 18 | Age > 18)

# write.csv(dados_datasetscomp,"dados_datasetscomp.csv")
```


# Decreasing rate

```{r}
dados_datasetscomp_rate <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL" | Diagnostic == "MCI"| Diagnostic == "AD", Sample != "IDOR-CCD-Control")
dados_datasetscomp_rate$Diagnostic <- factor(dados_datasetscomp_rate$Diagnostic, levels = c("CTL", "MCI","AD"))
dados_datasetscomp_rate$Sample <- as.factor(dados_datasetscomp_rate$Sample)

N_SUBJ <- dados_datasetscomp_rate %>% group_by(Diagnostic) %>% summarise(N_SUBJ = n_distinct(SUBJ))
```

## AvgThickness \~ Age

```{r cache=TRUE}
m.1 <- lme4::lmer(AvgThickness ~ Age * Diagnostic +(1|Sample) + (1|Sample:Diagnostic) , data = dados_datasetscomp_rate)

## performance::check_model(m.1)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

tableT <- full_join(mean, m.lstk, by = c("Diagnostic")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "T")

# m.lstk %>% mutate(
#     TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)),
#     CI = paste(signif(asymp.LCL, 2), ";", signif(asymp.UCL, 2)),
#   ) %>% dplyr::select(c(Diagnostic, TX, CI)) %>% full_join(N_SUBJ)
# 
# m.lstk %>% kable() %>% kable_styling()

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs %>% kable() %>% kable_styling()
 
ggplot(data = as_tibble(pairs), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.3, nudge_y = 0.0003) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'AvgT/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr()

e <- effect("Age:Diagnostic", m.1)
e <- as.data.frame(e)

ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "Avg Cortical Thickness", shape = "Diagnostic")

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="T variation", x = "Sample")

```

## K \~ Age

```{r cache=TRUE}
N_SUBJ <- dados_datasetscomp_rate %>% group_by(Diagnostic) %>% summarise(N_SUBJ = n_distinct(SUBJ))

m.1 <- lme4::lmer(K ~ Age * Diagnostic + (1|Sample) + (1|Sample:Diagnostic), data = dados_datasetscomp_rate)

# performance::check_model(m.1)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

tableK <- full_join(mean, m.lstk, by = c("Diagnostic")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "K")

# m.lstk %>% mutate(
#     TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)),
#     CI = paste(signif(asymp.LCL, 2), ";", signif(asymp.UCL, 2)),
#   ) %>% dplyr::select(c(Diagnostic, TX, CI)) %>% full_join(N_SUBJ) 
# m.lstk %>% kable() %>% kable_styling()

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs %>% kable() %>% kable_styling()
 
fig_TX_K_age <- ggplot(data = as_tibble(pairs), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.3, nudge_y = 0.0003) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'K/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr()

e <- effect("Age:Diagnostic", m.1)
e <- as.data.frame(e)
fig_K_age <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "K", shape = "Diagnostic")

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="K variation", x = "Sample")

```


# Harmonization

# Figures

```{r echo=FALSE}
T_shifta <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = AvgThickness, color = Sample))+
  geom_point() +
  theme_pubr() +
  labs(y = "T") +
  scale_x_continuous(limits = c(0,100))

T_shiftb <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = AvgThickness_shiftc, color = Sample)) +
  geom_point() +
  theme_pubr() +
  labs(y = "T (harmonized)") +
  scale_x_continuous(limits = c(0,100))

T_shift <- ggarrange(T_shifta, T_shiftb,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
T_shift
# # ggsave("GI_shift.pdf", plot = GI_shift, width = 18, height = 22, units = "cm", device = "pdf")
```


```{r echo=FALSE}
K_shifta <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K, color = Sample, alpha = 0.4))+
  geom_point() +
  theme_pubr() + 
  guides(alpha = "none") +
  scale_x_continuous(limits = c(0,100))

K_lifespan_a <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K, alpha = 0.4))+
    geom_point(aes(color = Sample, fill = Sample, alpha = 0.1)) +
    geom_smooth(method = "lm", color = "black") + geom_smooth(aes(color = Sample, fill = Sample), method = "lm") +
    theme_pubr() + 
    guides(alpha = "none") +
  scale_x_continuous(limits = c(0,100))

K_shiftb <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K_shiftc, color = Sample, alpha = 0.4))+
  geom_point() +
    guides(alpha = "none") + 
  theme_pubr() +
  labs(y = "K (harmonized)") +
  scale_x_continuous(limits = c(0,100))

K_lifespan_b <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K_shiftc, alpha = 0.4))+
    geom_point(aes(color = Sample, fill = Sample, alpha = 0.1)) +
    geom_smooth(method = "lm", color = "black") + geom_smooth(aes(color = Sample, fill = Sample), method = "lm") +
    guides(alpha = "none") + 
  theme_pubr() +
  labs(y = "K (harmonized)") +
  scale_x_continuous(limits = c(0,100))

K_shift <- ggarrange(K_shifta, K_shiftb,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
K_shift


K_lifespan <- ggarrange(K_lifespan_a, K_lifespan_b,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
K_lifespan

```


# After harmonization

```{r cache=TRUE}
amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Age_interval != "00-05", Age_interval != "95-100") %>%
    group_by(Age_interval) %>%
    do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_shiftc) + log10(TotalArea_shiftc) ~ log10(ExposedArea_shiftc), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Age_interval != "00-05", Age_interval != "95-100") %>%
    group_by(Age_interval) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>% filter(term == "log10(ExposedArea_shiftc)")

amostra_Coef$Age_intervalnumber <- as.numeric(factor(amostra_Coef$Age_interval))-1

cor.test(amostra_Coef$estimate, amostra_Coef$Age_intervalnumber)

cor.test(filter(amostra_Coef, Age_intervalnumber > 1)$estimate, filter(amostra_Coef, Age_intervalnumber > 1)$Age_intervalnumber)

fig_slope_ageinterval <- ggplot(amostra_Coef, aes(y = estimate, x = Age_interval)) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
    geom_point() +
  geom_line(group = 1) + 
  geom_hline(yintercept = 1.25, linetype = "dashed") +
    theme_pubr() + 
    theme(axis.title = element_text(size = 11),
          axis.text = element_text(size = 10),
          text = element_text(size = 10),
          axis.text.x = element_text(angle = 45, hjust = 1, size=9)
    ) + labs(y ="Slope (after harmonization)", x = "Age interval") +  geom_text(aes(label = N), nudge_y = 0.3)

fig_slope_ageinterval

ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL", Age_interval != "00-05", Age_interval != "95-100"), aes(y = K_shiftc, x = Age_interval), aes(y = K, x = Age_interval)) +
    geom_boxplot() + 
    theme_pubr() + 
    theme(axis.title = element_text(size = 11),
          axis.text = element_text(size = 10),
          text = element_text(size = 10),
          axis.text.x = element_text(angle = 45, hjust = 1, size=9)
    ) + labs(y ="K (after harmonization)", x = "Age interval")

```


```{r}
amostra_Coef <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL" | Diagnostic == "AD" , Age_interval != "00-05", Age_interval != "95-100") %>%
    group_by(Age_interval, Diagnostic) %>%
    do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_shiftc) + log10(TotalArea_shiftc) ~ log10(ExposedArea_shiftc), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"| Diagnostic == "AD" , Age_interval != "00-05", Age_interval != "95-100") %>%
    group_by(Age_interval, Diagnostic) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>% filter(term == "log10(ExposedArea_shiftc)")

amostra_Coef$Diagnostic <- factor(amostra_Coef$Diagnostic, levels=c('AD', 'CTL'))

ggplot(amostra_Coef, aes(y = estimate, x = Age_interval, color = Diagnostic)) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
    geom_point() + geom_hline(yintercept = 1.25, linetype = "dashed") +
    theme_pubr() + 
    theme(axis.title = element_text(size = 11),
          axis.text = element_text(size = 10),
          text = element_text(size = 10),
          axis.text.x = element_text(angle = 45, hjust = 1, size=9)
    ) + labs(y ="Slope (after harmonization)", x = "Age interval") +  geom_text(aes(label = N), nudge_y = 0.3)

amostra_Coef%>% dplyr::select(-c(term)) %>% kable() %>% kable_styling()

```

## AvgThickness \~ Age

```{r cache=TRUE}
m.1 <- lme4::lmer(AvgThickness_shiftc ~ Age * Diagnostic +(1|Sample) + (1|Sample:Diagnostic), data = dados_datasetscomp)

# performance::check_model(m.1)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

 lst <- m.lstk %>% mutate(
     TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableT <- full_join(mean, lst, by = c("Diagnostic")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "T_shiftc")
 
# m.lstk %>% mutate(
#     TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)),
#     CI = paste(signif(asymp.LCL, 2), ";", signif(asymp.UCL, 2)),
#   ) %>% dplyr::select(c(Diagnostic, TX, CI)) %>% full_join(N_SUBJ)

m.lstk %>% kable() %>% kable_styling()

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs %>% kable() %>% kable_styling()
 
ggplot(data = as_tibble(pairs), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.3, nudge_y = 0.0003) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'AvgT/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10), text = element_text(size = 10))

e <- effect("Age:Diagnostic", m.1)
e <- as.data.frame(e)

ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "Avg Cortical Thickness", shape = "Diagnostic") + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10), text = element_text(size = 10))

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="T variation", x = "Sample")

```


## K \~ Age

```{r cache=TRUE}
m.1 <- lme4::lmer(K_shiftc ~ Age * Diagnostic +(1|Sample) + (1|Sample:Diagnostic) , data = dados_datasetscomp)

# performance::check_model(m.1)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableK <- full_join(mean, lst, by = c("Diagnostic")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "K_shiftc")

# m.lstk %>% mutate(
#     TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)),
#     CI = paste(signif(asymp.LCL, 2), ";", signif(asymp.UCL, 2)),
#   ) %>% dplyr::select(c(Diagnostic, TX, CI)) %>% full_join(N_SUBJ) 
# m.lstk %>% kable() %>% kable_styling()

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs %>% kable() %>% kable_styling()
 
fig_TX_K_age_c <- ggplot(data = as_tibble(pairs), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.3, nudge_y = 0.0003) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'K/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10), text = element_text(size = 10))

e <- effect("Age:Diagnostic", m.1)
e <- as.data.frame(e)

fig_K_age_c <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "K", shape = "Diagnostic") + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10), text = element_text(size = 10))

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="K variation", x = "Sample")

```

