---
title: "Typical"
author: "Fernanda Hansen P. de Moraes"
date: "05/03/2021"
output: 
  html_document: 
    toc: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep.R")

dados_datasetscomp <- dados_datasetscomp %>% filter(Sample != "HCP500r")

# dados_datasetscomp <- dados_datasetscomp %>% filter(Age == 18 | Age > 18)

# write.csv(dados_datasetscomp,"dados_datasetscomp.csv")

data <- dados_datasetscomp %>% filter(Sample != "IDOR")

# write.csv(data,"data.csv")


```

# Datasets description

```{r description, echo=FALSE}
filter(dados_datasetscomp, Sample != "Mota&Houzel2015", ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

filter(dados_datasetscomp,
       Sample != "Mota&Houzel2015",
       ROI == "hemisphere") %>%
  group_by(Sample, Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
    AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()

```

```{r}
dados_datasetscomp$ROI <- factor(dados_datasetscomp$ROI, levels = c("hemisphere", "F", "O", "P", "T"))
```

# Results
```{r echo=TRUE}

filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(sqrt(AvgThickness) *TotalArea ~ ExposedArea, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(ExposedArea,sqrt(AvgThickness)*TotalArea)) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, k)) +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()



filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness) + log10(TotalArea) ~ log10(ExposedArea), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea), 1 / 2 * log10(AvgThickness) + log10(TotalArea))) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K)) +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()

```


```{r eval=FALSE, include=FALSE}
# Results - Lobes

filter(dados_datasetscomp, ROI != "hemisphere") %>%
  group_by(ROI, Diagnostic) %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_age_decay) + log10(TotalArea_age_decay) ~ log10(ExposedArea_age_decay), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = filter(slope, term == "log10(ExposedArea_age_decay)", Diagnostic == "CTL"), aes(x = estimate, alpha = 0.2)) +
    geom_histogram() + geom_vline(xintercept = 1.25, linetype = "dashed") +
    theme_pubr() +
  guides(alpha = FALSE)

ggplot(data = filter(slope, term == "log10(ExposedArea_age_decay)"), aes(x = estimate, alpha = 0.2, color = Diagnostic, fill = Diagnostic)) +
    geom_histogram() +
  geom_vline(xintercept = 1.25, linetype = "dashed") +
    theme_pubr() +
  guides(alpha = FALSE)
```


```{r eval=FALSE, include=FALSE}
slope <- filter(dados_datasetscomp, ROI != "hemisphere") %>%
  group_by(SUBJ, hemi, Sample, Diagnostic) %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness) + log10(TotalArea_corrected) ~ log10(ExposedArea_corrected), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = filter(slope, term == "log10(ExposedArea_corrected)", Diagnostic == "CTL"), aes(x = estimate, alpha = 0.2)) +
    geom_histogram() +
  geom_vline(xintercept = 1.25, linetype = "dashed") +
    theme_pubr()
+ guides(alpha = FALSE)

ggplot(data = filter(slope, term == "log10(ExposedArea_corrected)"), aes(x = estimate, alpha = 0.2, color = Diagnostic, fill = Diagnostic)) +
    geom_histogram() +
  geom_vline(xintercept = 1.25, linetype = "dashed") +
    theme_pubr() +
  guides(alpha = FALSE)
```

# Results - Harmonized
```{r }
filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_shiftc) + log10(TotalArea_shiftc) ~ log10(ExposedArea_shiftc), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea_shiftc), 1 / 2 * log10(AvgThickness_shiftc) + log10(TotalArea_shiftc))) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_point(aes(color = Sample)) +
  stat_regline_equation() +
  theme_pubr() 

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K_shiftc)) +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()
```

# Sanity check
```{r}
dados_datasetscomp <- filter(dados_datasetscomp, ROI == "hemisphere") %>% mutate(x = TotalArea_shiftc*AvgThickness_shiftc^(1/2), y = ExposedArea_shiftc^2) 
dados_datasetscomp %>%
  do(fit_amostra = tidy(lm(y ~ x, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = dados_datasetscomp, aes(TotalArea_shiftc*AvgThickness_shiftc^(1/2), ExposedArea_shiftc^2)) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()
```

# Deaging

```{r }
filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_age_decay) + log10(TotalArea_age_decay) ~ log10(ExposedArea_age_decay), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea_age_decay), 1 / 2 * log10(AvgThickness_age_decay) + log10(TotalArea_age_decay))) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_point(aes(color = Sample)) +
  stat_regline_equation() +
  theme_pubr() 


ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K_age_decay)) +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()
```


# Deaging + harmonization

```{r}
# source("deaging_harmonization.R")
```

```{r }
filter(dados_datasetscomp, ROI == "hemisphere") %>%
  do(fit_amostra = tidy(lm(1/2 * log10(AvgThickness_age_decay_shiftc) + log10(TotalArea_age_decay_shiftc) ~ log10(ExposedArea_age_decay_shiftc), data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
  unnest(fit_amostra)

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(log10(ExposedArea_age_decay_shiftc), 1 / 2 * log10(AvgThickness_age_decay_shiftc) + log10(TotalArea_age_decay_shiftc))) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_point(aes(color = Sample)) +
  stat_regline_equation() +
  theme_pubr() 

ggplot(data = filter(dados_datasetscomp, ROI == "hemisphere"), aes(Age, K_age_decay_shiftc)) +
  geom_point(aes(color = Sample)) +
    stat_regline_equation() +
  theme_pubr()
```

