---
title: "Typical"
author: "Fernanda Hansen P. de Moraes"
date: "05/03/2021"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
```

```{r preparo, message=FALSE, warning=FALSE, include=FALSE}
# PREPARO

# define a area de trabalho
setwd("C:/Users/ferna/Documents/idor/Gyrification/RRRRRR/comparing_samples/") # se no computador

# carrega os pacotes utilizados
source("01-call_packages.R")

# Chama funcoes caso necessário
source("02-funcoes.R")

# onde estao os arquivos de resultados:
path <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/long_tables/")

path_yujiangscript <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")

path_yujiangscript_newsurfaces <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/Wang_code_extraction/")
  
path_lobes <- str_c("C:/Users/ferna/Documents/idor/Gyrification/STATS/LobesScaling/")
 
path_sessions <- str_c("C:/Users/ferna/Documents/idor/Gyrification/Processamento_longitudinal/V6/data/")

Age.cor = 25

# Prepara os dados para analise
source("05-analises_prep.R")

dados_datasetscomp <- dados_datasetscomp %>% filter(Sample != "HCP500r")

# dados_datasetscomp <- dados_datasetscomp %>% filter(Age == 18 | Age > 18)

# write.csv(dados_datasetscomp,"dados_datasetscomp.csv")
```

# Decreasing rate

```{r}
dados_datasetscomp_rate <- filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL" | Diagnostic == "MCI"| Diagnostic == "AD")
dados_datasetscomp_rate$Diagnostic <- factor(dados_datasetscomp_rate$Diagnostic, levels = c("CTL", "MCI","AD"))
dados_datasetscomp_rate$Sample <- as.factor(dados_datasetscomp_rate$Sample)

N_SUBJ <- dados_datasetscomp_rate %>% group_by(Diagnostic) %>% summarise(N_SUBJ = n_distinct(SUBJ))
```

## AvgThickness \~ Age

```{r echo=FALSE}
m.1 <- lme4::lmer(AvgThickness ~ Age * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="T variation", x = "Sample")

re <- filter(re, grpvar == "Sample") %>% mutate(T_shift = condval, Sample = grp) %>% dplyr::select(-c(condval, grpvar, term, condsd, grp))

dados_datasetscomp_rate <- full_join(dados_datasetscomp_rate, re) %>% mutate(AvgThickness_shiftc = AvgThickness - T_shift)

```

## TotalArea \~ Age

```{r eval=FALSE, include=FALSE}
m.1 <- lme4::lmer(TotalArea ~ Age * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="AT variation", x = "Sample")

re <- filter(re, grpvar == "Sample") %>% mutate(AT_shift = condval, Sample = grp) %>% dplyr::select(-c(condval, grpvar, term, condsd, grp))

dados_datasetscomp_rate <- full_join(dados_datasetscomp_rate, re) %>% mutate(TotalArea = TotalArea - AT_shift)


```

## ExposedArea \~ Age

```{r eval=FALSE, include=FALSE}
m.1 <- lme4::lmer(ExposedArea ~ Age * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="AE variation", x = "Sample")

re <- filter(re, grpvar == "Sample") %>% mutate(AE_shift = condval, Sample = grp) %>% dplyr::select(-c(condval, grpvar, term, condsd, grp))

dados_datasetscomp_rate <- full_join(dados_datasetscomp_rate, re) %>% mutate(ExposedArea = ExposedArea - AE_shift)
```

```{r eval=FALSE, include=FALSE}
dados_datasetscomp_rate <- dados_datasetscomp_rate %>%
  mutate(
  k = sqrt(AvgThickness) * TotalArea / (ExposedArea ^ 1.25),
  K = 1 / 4 * log10(AvgThickness^2)  + log10(TotalArea) - 5 / 4 * log10(ExposedArea),
  S = 3 / 2 * log10(TotalArea) + 3 / 4 * log10(ExposedArea) - 9 /  4 * log10(AvgThickness^2) ,
  I = log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2) ,
  Knorm = K/sqrt(1 + (1/4)^2 + (5/4)^2),
  Snorm = S/sqrt((3/2)^2 + (3/4)^2 + (9/4)^2),
  Inorm = I/sqrt(1^2 + 1^2 + 1^2))
```

## K \~ Age

```{r}
m.1 <- lme4::lmer(K ~ Age * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="K variation", x = "Sample")

re <- filter(re, grpvar == "Sample") %>% mutate(K_shift = condval, Sample = grp) %>% dplyr::select(-c(condval, grpvar, term, condsd, grp))

dados_datasetscomp_rate <- full_join(dados_datasetscomp_rate, re) %>% mutate(K_shiftc = K - K_shift)
```

```{r}
K_shifta <- ggplot(filter(dados_datasetscomp, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K, color = Sample))+
  geom_point() +
  theme_pubr() + 
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
  ) 

K_shiftb <- ggplot(filter(dados_datasetscomp_rate, ROI == "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K_shiftc, color = Sample))+
  geom_point() +
  theme_pubr() + 
  theme(
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10)
  ) + labs(y = "K (shift removed)")


K_shift <- ggarrange(K_shifta, K_shiftb,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
K_shift
ggsave("K_shift.png", plot = K_shift, width = 18, height = 22, units = "cm", device = "png")
```

```{r}
m.1 <- lme4::lmer(K_shiftc ~ Age * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

tableK <- full_join(mean, m.lstk, by = c("Diagnostic")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "K")

m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)),
    CI = paste(signif(asymp.LCL, 2), ";", signif(asymp.UCL, 2)),
  ) %>% dplyr::select(c(Diagnostic, TX, CI)) %>% full_join(N_SUBJ) 
m.lstk %>% kable() %>% kable_styling()

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs %>% kable() %>% kable_styling()
 
ggplot(data = as_tibble(pairs), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.3, nudge_y = 0.0003) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'K/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10), text = element_text(size = 10))

e <- effect("Age:Diagnostic", m.1)
e <- as.data.frame(e)
ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "K", shape = "Diagnostic") + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10), text = element_text(size = 10))

re <- as_tibble(ranef(m.1))

ggplot(filter(re, grpvar == "Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) + labs(y ="K variation", x = "Sample")

ggplot(filter(re, grpvar == "Diagnostic:Sample"), aes(y = condval, x = as.character(grp))) +
  geom_errorbar(aes(ymin = condval+1.96*condsd, ymax = condval-1.96*condsd), width = 0.2) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() + 
  theme(axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  )
```

## S \~ Age

```{r eval=FALSE, include=FALSE}
m.1 <- lme4::lmer(S ~ Age * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

# performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

re <- as_tibble(ranef(m.1)) 

re <- filter(re, grpvar == "Sample") %>% mutate(S_shift = condval, Sample = grp) %>% dplyr::select(-c(condval, grpvar, term, condsd, grp))

dados_datasetscomp_rate <- full_join(dados_datasetscomp_rate, re, by=c("Sample")) %>%
  mutate(S_shiftc = S - S_shift)

```

```{r}
dados_datasetscomp_rate$S_shiftc
```

## I \~ Age

```{r eval=FALSE, include=FALSE}
m.1 <- lme4::lmer(I ~ Age * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

re <- as_tibble(ranef(m.1))

re <- filter(re, grpvar == "Sample") %>% mutate(I_shift = condval, Sample = grp) %>% dplyr::select(-c(condval, grpvar, term, condsd, grp))

dados_datasetscomp_rate <- full_join(dados_datasetscomp_rate, re) %>% mutate(I_shiftc = I - I_shift)

```

```{r}
dados_datasetscomp_rate$S_shiftc
```


# Age error
## AvgThickness \~ Age

```{r}
m.1 <- lme4::lmer(Age ~ AvgThickness_shiftc * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

# performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

```

```{r}
dados_datasetscomp_rate$S_shiftc
```

## K \~ Age

```{r}
m.1 <- lme4::lmer(Age ~ K_shiftc * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

# performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

```

```{r}
dados_datasetscomp_rate$S_shiftc
```

## S \~ Age

```{r}
m.1 <- lme4::lmer(Age ~ S_shiftc * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

# performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

```

## I \~ Age

```{r}
m.1 <- lme4::lmer(Age ~ I_shiftc * Diagnostic + (1|Sample/Diagnostic), data = dados_datasetscomp_rate)

# performance::check_model(m.1)

anova(m.1)
summary(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

```