---
title: "idade_25"
author: "Fernanda Hansen"
date: "17 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# gerar o fator de correcao para area total, area externa e espessura media

## area total
```{r area total, echo=TRUE}
# taxa de caimento da girificacao (log K teorico)----

decay_TotalArea <- filter(dados_hemi_v1, Visit == 1)  %>%
  group_by(Diagnostic) %>%
  do(fit_decay_TotalArea = lm(TotalArea ~ Age, data = .))

# get the coefficients por intervalo de idade ----
decay_TotalArea_Coef = tidy(decay_TotalArea,
                               fit_decay_TotalArea,
                conf.int = TRUE,
                conf.level = 0.95)
decay_TotalArea_Coef

decay_TotalArea_Pred = augment(decay_TotalArea, fit_decay_TotalArea)
decay_TotalArea_Pred

decay_TotalArea_R2 = glance(decay_TotalArea, fit_decay_TotalArea)
decay_TotalArea_R2

# lambda, b e Ko

lambda_At_CTL <- decay_TotalArea_Coef$estimate[6]
b_At_CTL <- decay_TotalArea_Coef$estimate[5]
Ato_CTL <- exp(b_At_CTL)

lambda_At_CCL <- decay_TotalArea_Coef$estimate[4]
b_At_CCL <- decay_TotalArea_Coef$estimate[3]
Ato_CCL <- exp(b_At_CCL)

lambda_At_ALZ <- decay_TotalArea_Coef$estimate[2]
b_At_ALZ <- decay_TotalArea_Coef$estimate[1]
Ato_ALZ <- exp(b_At_ALZ)
```

## area externa
```{r area externa, echo=TRUE}
# taxa de caimento da girificacao (log K teorico)----

decay_SmoothArea <- filter(dados_hemi_v1, Visit == 1)  %>% 
  group_by(Diagnostic) %>%
  do(fit_decay_SmoothArea = lm(ExposedArea ~ Age, data = .))

# get the coefficients por intervalo de idade ----
decay_SmoothArea_Coef = tidy(decay_SmoothArea,
                               fit_decay_SmoothArea,
                conf.int = TRUE,
                conf.level = 0.95)
decay_SmoothArea_Coef

decay_SmoothArea_Pred = augment(decay_SmoothArea, fit_decay_SmoothArea)
decay_SmoothArea_Pred

decay_SmoothArea_R2 = glance(decay_SmoothArea, fit_decay_SmoothArea)
decay_SmoothArea_R2

# lambda, b e Ko

lambda_Ae_CTL <- decay_SmoothArea_Coef$estimate[6]
b_Ae_CTL <- decay_SmoothArea_Coef$estimate[5]
Ato_CTL <- exp(b_Ae_CTL)

lambda_Ae_CCL <- decay_SmoothArea_Coef$estimate[4]
b_Ae_CCL <- decay_SmoothArea_Coef$estimate[3]
Ato_CCL <- exp(b_Ae_CCL)

lambda_Ae_ALZ <- decay_SmoothArea_Coef$estimate[2]
b_Ae_ALZ <- decay_SmoothArea_Coef$estimate[1]
Ato_ALZ <- exp(b_Ae_ALZ)
```

## area espessura
```{r area externa, echo=TRUE}
# taxa de caimento da girificacao (log K teorico)----

decay_SmoothArea <- filter(dados_hemi_v1, Visit == 1)  %>% 
  group_by(Diagnostic) %>%
  do(fit_decay_SmoothArea = lm(ExposedArea ~ Age, data = .))

# get the coefficients por intervalo de idade ----
decay_SmoothArea_Coef = tidy(decay_SmoothArea,
                               fit_decay_SmoothArea,
                conf.int = TRUE,
                conf.level = 0.95)
decay_SmoothArea_Coef

decay_SmoothArea_Pred = augment(decay_SmoothArea, fit_decay_SmoothArea)
decay_SmoothArea_Pred

decay_SmoothArea_R2 = glance(decay_SmoothArea, fit_decay_SmoothArea)
decay_SmoothArea_R2

# lambda, b e Ko

lambda_Ae_CTL <- decay_SmoothArea_Coef$estimate[6]
b_Ae_CTL <- decay_SmoothArea_Coef$estimate[5]
Ato_CTL <- exp(b_Ae_CTL)

lambda_Ae_CCL <- decay_SmoothArea_Coef$estimate[4]
b_Ae_CCL <- decay_SmoothArea_Coef$estimate[3]
Ato_CCL <- exp(b_Ae_CCL)

lambda_Ae_ALZ <- decay_SmoothArea_Coef$estimate[2]
b_Ae_ALZ <- decay_SmoothArea_Coef$estimate[1]
Ato_ALZ <- exp(b_Ae_ALZ)
```

